### ISSUE TITLE
Bug: Knowledge Base can not change page

### ISSUE THREAD

**Issue by frankenstein91** [nilsteampassnet/TeamPass#1069]
Hi,
i'm using the current master branche from github. 
I can not change the page in the Knowlege Base. 
"Showing 1 to 10 of 10 entries (filtered from 11 total entries)" but the only one page.

**Comment by nilsteampassnet** [comment]
This bug is corrected in 2.1.24

**Comment by frankenstein91** [comment]
@nilsteampassnet please reopen this issue. The problem still exists in 2.1.5.2.
![2016-02-05 08_22_10-teampass](https://cloud.githubusercontent.com/assets/2527348/12840304/96dd7d28-cbe2-11e5-859d-10b441bb4767.png)
I use Firefox 43.0.4.
