### ISSUE TITLE
"Error Encryption of the Password" after update from 2.1.23.4 to 2.1.24 

### ISSUE THREAD

**Issue by kefiiir** [nilsteampassnet/TeamPass#1086]
Setps to reproduce:
-update teampass from 2.1.23.4 to 2.1.24 (development branch e7479a2  )
-open http://server/teampass/install/upgrade.php 
-passe all steps without errors
-login like admin and turn of maintenance mode
-log in like normal user

All passwords have a red triangle ant tip "Error Encryption of the Password"

any suggestions?

**Comment by kefiiir** [comment]
if restore database from backup - everything is ok. But update it - "Error Encryption of the Password"

**Comment by dam09fr** [comment]
I'm having the same problem the same situation after upgrading to 2.1.24.1 from development (pre-producton 2.1.24).

**Comment by nilsteampassnet** [comment]
​Are your passwords​ empty?

**Comment by dam09fr** [comment]
No, the db record is not empty.

**Comment by nilsteampassnet** [comment]
​What I mean is, when you have selected an item so that you can see its
details, is the password string empty when you click on the "eye" icon?

**Comment by dam09fr** [comment]
When I click on the item, I can see the "eye icon" and the stars. If I click on the eye, it disappears.
See screenshots : 
 - Element clicked in list : http://img11.hostingpics.net/pics/6222552015111912h1410.jpg
 - Click on eye icon : http://img11.hostingpics.net/pics/2988982015111912h1423.jpg

I can reproduce the problem when launching an upgrade with an item createn in 2.1.24.0 and doing the upgrade to 2.1.24.2 ...

**Comment by nilsteampassnet** [comment]
​No change of sk.php file?

**Comment by dam09fr** [comment]
No, my sk.php is exactly the same after the upgrade.

**Comment by kefiiir** [comment]
the same situation with upgrade to 2.1.24.4

**Comment by nilsteampassnet** [comment]
​I have committed the fix for this issue in branch fix_2.1.24

@kefiiir, Can you please confirm it fixes your point?

**Comment by dam09fr** [comment]
I did some tests this morning on the branch "fix_2.1.24" ... problem solved!
Thank you !

**Comment by hexxamillion** [comment]
I applied the fix and it works for personal items that are on the root of my personal folder. For personal items that are within folders the problem still exists.
