### ISSUE TITLE
Login failure gives odd error

### ISSUE THREAD

**Issue by ahh3ah** [nilsteampassnet/TeamPass#1144]
Hi,

On 2.1.24.4, when a password is entered incorrectly, the following is the error that is displayed

[object Object] login attempts on 4

[object Object], I assume should read 'Login Failure'.

Tommy

**Comment by nilsteampassnet** [comment]
​Corrected in 2.1.25

**Comment by girishkg** [comment]
This is still reproducable in 2.1.25

[object Object] login attempts on 11

![teampass_err](https://cloud.githubusercontent.com/assets/4685602/14669048/b658957c-0704-11e6-94c3-cd0ff00744b8.png)
