### ISSUE TITLE
Administrator has no access to Items

### ISSUE THREAD

**Issue by phearomsin** [nilsteampassnet/TeamPass#2004]
I tried to enable Administrator to have access to Items by editing the file include.php in folder /includes/config/ as on [Teampass Documentation](https://teampass.readthedocs.io/en/latest/install/setup/) and when I logged in with admin user I can see that the **Password** and **Search** menu are available, but Administrator still has not access to the Items and Folders.

### Server configuration

**Teampass version:** 
2.1.27.9

#### Web server error log
```
[Fri Nov 10 16:23:53.559064 2017] [:error] [pid 11977] [client xx.xx.xx.xx:52520] PHP Notice:  Undefined index: no_access_folders in /var/www/teampass/sources/tree.php on line 312, referer: https://teampass.example.com/index.php?page=items
[Fri Nov 10 16:23:53.559154 2017] [:error] [pid 11977] [client xx.xx.xx.xx:52520] PHP Warning:  array_merge(): Argument #3 is not an array in /var/www/teampass/sources/tree.php on line 313, referer: https://teampass.example.com/index.php?page=items
[Fri Nov 10 16:23:53.559220 2017] [:error] [pid 11977] [client xx.xx.xx.xx:52520] PHP Warning:  in_array() expects parameter 2 to be array, null given in /var/www/teampass/sources/tree.php on line 314, referer: https://teampass.example.com/index.php?page=items

[Fri Nov 10 16:23:58.993302 2017] [:error] [pid 11977] [client xx.xx.xx.xx:52520] PHP Warning:  array_merge(): Argument #3 is not an array in /var/www/teampass/sources/items.queries.php on line 2304, referer: https://teampass.example.com/index.php?page=items
[Fri Nov 10 16:23:58.993479 2017] [:error] [pid 11977] [client xx.xx.xx.xx:52520] PHP Warning:  in_array() expects parameter 2 to be array, null given in /var/www/teampass/sources/items.queries.php on line 2305, referer: https://teampass.example.com/index.php?page=items
```

![image](https://user-images.githubusercontent.com/33160904/32649563-144523ce-c62d-11e7-9ec5-92619e677804.png)

**Comment by nilsteampassnet** [comment]
Please upgrade using development branch.

**Comment by phearomsin** [comment]
It works now.
But I have other problem of show_description in item listings. **Show item description field in item listings** options is disable, but item description is still showing in item listings.

**Comment by nilsteampassnet** [comment]
Ok. I have fixed it too.

**Comment by vitich** [comment]
Sad but not fixed... admin does not have access to items:

You are not allowed to see this page.
