### ISSUE TITLE
LDAP Integration - "No Options" / Rotating Cog / "Login credentials do not correspond!"

### ISSUE THREAD

**Issue by SFIF1** [nilsteampassnet/TeamPass#2006]
### Steps to reproduce
1. Fresh installation of TeamPass 2.1.27.9
2. Basic settings configured
3. LDAP settings configured as per example data in attached screenshot
4. Attempt to login with a valid AD user

### Expected behaviour
It is understood that the AD user should be able to login, which subsequently creates the personal / private folder

### Actual behaviour
1. When LDAP settings have been configured and the "Start" button clicked, "No Options" appears briefly and then fades away.
2. When a valid AD user attempts to login, one of two conditions happen;
2.1 The cog continuously rotates alongside "Please identify yourself"
2.2 "Login credentials do not correspond!" is displayed

**Configuration Example:**
![image](https://user-images.githubusercontent.com/33545543/32656473-db83d6ac-c609-11e7-946a-bb56b89e6c49.png)

**Login Example:**
![image](https://user-images.githubusercontent.com/33545543/32656520-08f8caa2-c60a-11e7-8878-a5f7b770f25e.png)

I have tried PHP 5.6.31, 7.0.23 and 7.1.9.
I have tried to manually set the LDAP configuration within _identify.php_.
I have read multiple issues logged on this GitHub Project, which include the following:

- https://github.com/nilsteampassnet/TeamPass/issues/1948
- https://github.com/nilsteampassnet/TeamPass/issues/1973
- https://github.com/nilsteampassnet/TeamPass/issues/1805
- https://github.com/nilsteampassnet/TeamPass/issues/1708
- https://github.com/nilsteampassnet/TeamPass/issues/1511
- https://github.com/nilsteampassnet/TeamPass/issues/1486

Any and all help would be much appreciated.

### Server configuration
**Operating system**: Windows 7 (PoC O/S)

**Web server:** Apache 2.4.27

**Database:** MySQL 5.7.19

**PHP version:** PHP 5.6.31

**Teampass version:** 2.1.27.9

**Teampass configuration file:** Contents verified and does include the correct LDAP values

**Updated from an older Teampass or fresh install:** First & Fresh Installation
PLEASE attach to this message the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Google Chrome & Internet Explorer

**Operating system:** Windows 7

#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
Please enable ldap debug.
From identify.php file, change `$debugDuo = 0;` to `$debugDuo = 1;`
Run authentication and check newly created file ldap.debug.txt.

Investigate from it.

As it is a fresh install, you should use the development branch as I will package the new version this weekend.

**Comment by SFIF1** [comment]
Thank you very much for the swift reply.

I have now enabled debugging on both $debugLdap and $debugDuo.

The output is as follows (amended to protect sensitive data):

**ldap.debug.txt**

Get all LDAP params : 
mode : 1
type : windows
base_dn : OU=Subgroup,OU=UserGroup,DC=domain,DC=com
search_base : 0
bind_dn : 
bind_passwd : 
user_attribute : 0
account_suffix : @domain.com
domain_controllers : DC-1.domain.com,DC-2.domain.com,DC-3.domain.com
port : 636
use_ssl : 1
use_tls : 0
*********
Get all ldap params : 
base_dn : OU=Subgroup,OU=UserGroup,DC=domain,DC=com
account_suffix : @domain.com
domain_controllers : DC-1.domain.com,DC-2.domain.com,DC-3.domain.com
port : 636
use_ssl : 1
use_tls : 0
*********
Create new adldap object : Success
After authenticate : Can't contact LDAP server
ldap status : 
*********

**ldap.debug.txt**

Content of data sent 'LONG STRING HERE'
Starting authentication of 'User.Name'
LDAP status: 1
USer exists: 0
*********

**Comment by nilsteampassnet** [comment]
It seems that the given credentials for LDAP are not exact.
Indeed the LDAP server couldn't be reached.

Please cross-check the data.

**Comment by nilsteampassnet** [comment]
I think perhaps it comes from the multi-groups you are indicating in base-DN.
Can you try with only one group?

- LDAP account Suffix: @my-domain.de
- LDAP base DN: DC=my-domain,DC=de
- LDAP domain controllers(s): dc1.my-domain.de,dc1.another-domain.local

Regarding LDAPS, are you sure? try also with TLS.

What you could also do is to upgrade with development branch. I have added new field for `LDAP allowed user group `.

**Comment by phearomsin** [comment]
I try with this settings, it works for me.

- LDAP server type: Posix / OpenLDAP (RFC2307) Search Based
- LDAP account suffix for your domain: @dc=example,dc=com
- Class to search: posixAccount
- User attribute to search: uid
- LDAP search base: ou=people,dc=example,dc=com
- LDAP domain controller(s): directory.example.com
- LDAP port: 636
- Use LDAP through SSL (LDAPS): Yes
- Use LDAP through TLS: Yes

**Comment by SFIF1** [comment]
Thank you for your replies.

I have made the changes you recommended but unfortunately it does not function.

> Regarding LDAPS, are you sure? try also with TLS.
Yes, I have configured other applications to connect via LDAPS successfully.

Does the application use any service account in the background to first make the call / successful authentication with LDAP before attempting to process the user who wishes to login?

I understand that the error suggests it cannot contact the LDAP server, however using these settings with _a different application_ it connects successfully.

> What you could also do is to upgrade with development branch. I have added new field for LDAP allowed user group.

As I do not wish to overwrite the configuration work I have already completed, please can you advise how I may upgrade to this development branch safely?

Many thanks...

**Comment by SFIF1** [comment]
FYI:

Get all LDAP params : 
mode : 1
type : windows
base_dn : DC=domain,DC=com
search_base : 0
bind_dn : 
bind_passwd : 
user_attribute : 0
account_suffix : @domain.com
domain_controllers : DC-1.domain.com,DC-2.domain.com,DC-3.domain.com
port : 636
use_ssl : 1
use_tls : 1
*********
Get all ldap params : 
base_dn : DC=domain,DC=com
account_suffix : @domain.com
domain_controllers : DC-1.domain.com,DC-2.domain.com,DC-3.domain.com
port : 636
use_ssl : 1
use_tls : 1
*********
Create new adldap object : Can't contact LDAP server
After authenticate : Can't contact LDAP server
ldap status :

**Comment by SFIF1** [comment]
Also to confirm; the user I am trying to login with does not yet exist within TeamPass, but I expect it to be created on first login.

**Comment by Deaton64** [comment]
Hello,
Sorry to jump on your thread, but I was also having the same issue with version 2.1.27.9.
I just tried the latest development version and when I test the settings, I get a spinning cog forever and this in the Apache log file: `PHP Parse error:  syntax error, unexpected ''ldap_port'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in /var/www/html/teampass/includes/config/tp.config.php on line 121`  
That's with the port of 636 and in the config file, that's what the value is set to.

OS=Centos 7, LDAP to Windows AD, MySQL=5.5.56-MariaDB, Apache 2.4.6, PHP=5.6.31

**Comment by nilsteampassnet** [comment]
@dam09fr, I could not reproduce but I think I have found something in the code that could lead to what you faced depending on server configuration. I've created a new 2.1.27.10 package.
If you previously upgraded to this new version, you just have to overwrite the existing files with the new package.

**Comment by Qwerty999999** [comment]
Hello,
I have the same problem with version 2.1.27.10 

teampass work correctly on 2.1.27.x (opensuse 13.2, php 5.6.1.89.1, mysql 5.6.34-2.23.1 )

update path 2.1.27.x->2.1.27.5->2.1.27.9->2.1.27.10
on 2.1.25 ldap didn't work

I tried change base_dn and account_suffix with various notations

Get all LDAP params : 
mode : 1
type : windows
base_dn : dc=domain,dc=com,dc=cc
search_base : 
bind_dn : 
bind_passwd : 
user_attribute : 0
account_suffix : @dc=domain,dc=com,dc=cc
domain_controllers : ads01.domain.com.cc,ads02.domain.com.cc
port : 389
use_ssl : 0
use_tls : 0
*********

Get all ldap params : 
base_dn : dc=domain,dc=com,dc=cc
account_suffix : @dc=domain,dc=com,dc=cc
domain_controllers : ads01.domain.com.cc,ads02.domain.com.cc
port : 389
use_ssl : 0
use_tls : 0
*********

Create new adldap object : Success
After authenticate : Invalid credentials
ldap status : 



Content of data sent 'xxx'
Starting authentication of 'domain\aligator'
LDAP status: 1
USer exists: 0


OS VERSION updated after install last 2.1.27.10

opensuse 42.3 (updated from 13.2)
php 7 (updated from 5.6.1.89.1)
mysql 5.6.38 (updated from 5.6.34-2.23.1)

**Comment by sshipway** [comment]
Just to note that I am seeing this as well when I try to integrate with our LDAP.  I will run some more check to be absolutely certain I'm using the correct credentials, though

**Comment by TomaszMru** [comment]
Hi I had same issue, resolution was past all field again. In debuger i saw the port was not set despite  configuration in web console.

**Comment by tecjms** [comment]
I am experiencing the exact same issue with 2.1.27.10

Has anyone been able to resolve this issue?  What steps did you take?

**Comment by nilsteampassnet** [comment]
@tecjms you should share your parameters

**Comment by tecjms** [comment]
MySQL version: 5.7.19
 
 PHP version: 5.6.31
 
 Teampass version: 2.1.27 


LDAP configuration

LDAP server type: Windows / Active Directory  
LDAP account suffix for your domain: @msw.domain.net
LDAP base DN for your domain: DC=msw,DC=domain,DC=net
LDAP allowed user group CN: OU=Users,OU=Users,OU=domain on-site,DC=msw,DC=domain,DC=net
LDAP domain controller(s): dc1.msw.domain.net
LDAP port: 636
Use LDAP through SSL (LDAPS): Yes
Use LDAP through TLS: No
Teampass local users only: No
Hide forgot password link on Home page: No
Newly created user is administrated by: Administrator

Test current configuration 

Username to use for testing purpose: testusr
Username password: <password>
No username needed: unchecked

I have verified that this configuration works by inputing the above perimeters in a LDAP Directoy Browser (third party) named LDAPAdmin
 When clicking the gear icon I get a brief spinning gear followed by "No Options"

Enabled duo.debug and ldap.debug

duo.debug.txt results:
Content of data sent '
Starting authentication of 'domain\testuser'
LDAP status: 1
USer exists: 0
'
Starting authentication of 'testuser'
LDAP status: 1
USer exists: 1
Proceed with Ident: 1
User's password verified: 


----
Identified : false

Content of data sent ''
Starting authentication of 'domain\testuser'
LDAP status: 1
USer exists: 0
Content of data sent ''
Starting authentication of 'domain\testuser'
LDAP status: 1
USer exists: 0
Content of data sent ''
Starting authentication of 'admin'
LDAP status: 1
USer exists: 1
Proceed with Ident: 1
User's password verified: 1
User's token: ahgh0Chie7fe4aF6pi8re4aiCh3hee8ohquai0Ahf1Ahph0bin
Preparing to identify the user rights


----
Identified : CfBMn06ncN

Content of data sent  'domain\testuser'
LDAP status: 1
USer exists: 0
Content of data sent '
Starting authentication of 'admin'
LDAP status: 1
USer exists: 1
Proceed with Ident: 1
User's password verified: 1
User's token: 
Preparing to identify the user rights


----
Identified : 

Content of data sent 
Starting authentication of 'admin'
LDAP status: 1
USer exists: 1
Proceed with Ident: 1
User's password verified: 1
User's token: 
Preparing to identify the user rights


----
Identified : 

ldap.debug.txt results:
Get all LDAP params : 
mode : 1
type : windows
base_dn : DC=msw,DC=domain,DC=net
search_base : 0
bind_dn : 
bind_passwd : 
user_attribute : 0
account_suffix : @msw.domain.net
domain_controllers : dc1.msw.domain.net
port : 636
use_ssl : 1
use_tls : 0
*********

**Comment by tecjms** [comment]
tecjms  commented 28 days ago

**Comment by whositwhatnow** [comment]
anyone have updates on this ?

**Comment by nilsteampassnet** [comment]
Yes. It is solved in latest package.

**Comment by ishaffer2501** [comment]
Negative. I am running 2.1.27.16 and the issue is not solved.

**Comment by nilsteampassnet** [comment]
Please check your settings.
There must be something wrong or at least not written as expected.

**Comment by ishaffer2501** [comment]
Get all ldap params: 
- base_dn : OU=group,DC=xxxx,DC=xxxx
- account_suffix : @xxxx.xxxx
- domain_controllers : myserver.xxxx.xxxx
- ad_port : 389
- use_ssl : 0
- use_tls : 0
*********
Create new adldap object : Success

After authenticate : Success

ldap status : Successfull


Results of using an Active Directory user
"Login credentials do not correspond!"

**Comment by nilsteampassnet** [comment]
What version of teampass?

Try the IP of the domain controller?

**Comment by ekspp** [comment]
Hello fellows
I have the same issue. After new install (release 2.1.27.17), I have configured AD authentication. But Active Directory users can't login to teampass. The following message is shown: "Login credentials do not correspond!".
After some research and comparing code of different releases it looks like I found the fragment of code in identify.php which causes this behavior. It is user expiration check, see lines 764-768 in identify.php file. The IF condition is true so exit() is executed.
I have tried to commented this fragment and now AD users are able to login.
I can't clearly understand how this check works, but hope this information will help to fix issue.
![teampass](https://user-images.githubusercontent.com/42471363/44272171-c1efe380-a244-11e8-8d7f-5cce01d5e8ee.png)

**Comment by tuxlinuxbr** [comment]
I has the same problema and I did the same as @ekspp  and works for me too!

**Comment by rimk97** [comment]
The same problem with the version 2.1.27.22 i made the same modif and it works !

**Comment by Balaviyer** [comment]
I have commented ton the files mentioned by #ekspp, but I am still facing the issue

output of duo.debug.txt

Content of data sent 'FANX3L3dLFwgDGaXA/8zRY43LpEXrWIgoKlKb9w+ZfrpV8d9Oy1nph60Uo3cSJq8P8HCeHZmFn+Fo35Vpu/0DdO+n2hTLzdDeTr+zEEtrXx4FtC1ltSslN5pdb8uQvs0rBRSUf1UgF0FO861XC9OdMpslExzRV41KuCU1IBCLMosho8PTUgIpJFgU63gBMGXTjXAudMHIXYmJWfxZ77lW6HaKYSY/o6EWP+zZG8B989iSxN7cm2DSUI/N/NklyzKHNhCocOi0L8pHTARUBBe90w82RUmMWQ3b9r8RyJN2HPOVavvi3WelcaGQ38dhybGoeh9zVgAlQb2'
Starting authentication of 'bala.iyer'
LDAP status: 1
USer exists: 0

output of ldap.debug.txt

Create new adldap object : Success
After authenticate : Success
ldap status :
