### ISSUE TITLE
Users and Folders lists are empty in web interface

### ISSUE THREAD

**Issue by lukek-imm** [nilsteampassnet/TeamPass#2060]
Steps to reproduce:
1. Open Users or Folders tabs on the web interface
2. Nothing is listed

Expected behaviour:
Would expect to see lists under Users and Folders tabs

Actual behaviour:
On web interface there is nothing displayed under Users or Folders tabs - I can however see these items in the SQL database, and when I try to link other things to them (e.g. Under the Share User Rights option).

Server configuration:

Operating system:
Ubuntu Server 16.04

Web server:
Apache/2.4.18

Database:
MySQL 5.7.20

PHP version:
7.0.22

Teampass version:
2.1.27.10

Updated from an older Teampass or fresh install:
Fresh install

Client configuration:

Browser:
Tried multiple browsers, including Firefox and Safari

Operating system:
MacOS Sierra 10.12.6

**Comment by nilsteampassnet** [comment]
Can you provide the error logs as expected to help you ?

**Comment by lukek-imm** [comment]
Sorry, this is what I'm seeing this morning:

[Tue Dec 19 06:25:03.086849 2017] [mpm_prefork:notice] [pid 1719] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Tue Dec 19 06:25:03.086892 2017] [core:notice] [pid 1719] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 19 08:56:06.625028 2017] [:error] [pid 3728] [client xxx.xxx.xxx.xxx:xxxx] PHP Notice:  Undefined index: pwComplexity in /var/www/html/TeamPass/index.php on line 818, referer: https://teampass.imm.ox.ac.uk/logout.php

**Comment by YuNShiiRo** [comment]
Hello guys,

I encountered the same issue, and it was solved by following what Nil commented in the issue #1905 : by replace http by https in the config page of TeamPass !

Don't know if you already set this, but I hope you'll get it working.

**Comment by lukek-imm** [comment]
Hi YuNShiiRo, 
Thanks for the advice.
I hadn't set those to https rather than http, but on changing these I'm still having the same issue I was having before anyway.

**Comment by YuNShiiRo** [comment]
OK.

I just remember that I also checked the file includes/libraries/csrfp/libs/csrfp.config.php as explained in issue [1887](https://github.com/nilsteampassnet/TeamPass/issues/1887), to also have https.

It could be a CSRF protection issue.

Good luck.

**Comment by lukek-imm** [comment]
I changed (as it said on the Common Errors page) a moment ago while looking at the other settings you suggested.

Thanks for the help!

**Comment by nilsteampassnet** [comment]
Please provide the errors you get when opening those pages.
The errors previously shown don't fit what you are explaining.

**Comment by lukek-imm** [comment]
I don't see any errors on opening those pages, I just don't see any of the items on those pages either.

**Comment by lukek-imm** [comment]
![screen shot 2017-12-20 at 09 34 12](https://user-images.githubusercontent.com/34655243/34200449-0a3dca9c-e569-11e7-8577-ded0e5df86d7.png)
![screen shot 2017-12-20 at 09 34 35](https://user-images.githubusercontent.com/34655243/34200451-0a62a380-e569-11e7-8fbb-ac3899a058b1.png)

**Comment by lukek-imm** [comment]
Yes an Admin.

**Comment by nilsteampassnet** [comment]
If the tables are empty and that you have users then it means some error occurred.
You must track them.

For this, you can use the webbrowser console, use the tab "network" and check the answers from the server. Without them, I cannot help.
You should also check the apache error log that contain also certainly errors.

**Comment by pkoevesdi** [comment]
I had exactly the same problem. In my setup, the port of the teampass installation is changed from 443 to 444. So, the adress is https://servername:444. This was not reflected on the first configuration page. After putting the port in every field that refers to the server address, it worked!
These were the fields:
TeamPass location (URL) 
Upload folder (URL)
Files folder (URL)  
Favicon (full URL)

**Comment by pkoevesdi** [comment]
P.S. I also changed it in
\includes\libraries\csrfp\libs\csrfp.config.php

**Comment by phess1** [comment]
I had this same issue.  On the config page all my URLs are using the IP address.  When I access the server via server name,  I experience this issue.  When I access it via IP I do not have the issue.  When I changed the URLs to use server name on the config page,  I can no longer get to the login page at all.  I get an error regarding csrfp  but I made sure it was changed there too.  Im just going to use IP address for now because that is working.

**Comment by phess1** [comment]
error when using servername in URLs instead of IP

<?php /** * Configuration file for CSRF Protector z */ return array( "CSRFP_TOKEN" => "251008d56f376f29aa4a531e5fd8e956c08f561acb1cfda596", "logDirectory" => "../log", "failedAuthAction" => array( "GET" => 0, "POST" => 0), "errorRedirecti> "", "customErrorMessage" => "", "jsPath" => "../js/csrfprotector.js", "jsUrl" => "http://saasmonitor/teampass/includes/libraries/csrfp/js/csrfprotector.js", "tokenLength" => 50, "disabledJavascriptMessage" => "This site attempts to protect users against Cross-Site Request Forgeries attacks. In order to do so, you must have JavaScript enabled in your web browser otherwise this site will fail to work correctly for you. See details of your web browser for how to enable JavaScript.", "verifyGetFor" => array("*type=duo_check*", "*upload.attachments.php*", "*upload.files.php*") );

**Comment by nilsteampassnet** [comment]
Check carefully [this page](http://teampass.readthedocs.io/en/latest/errors/)

**Comment by Nathu2018** [comment]
Facing issue similar to lukek-imm posted with screen shot 

Please help

ND

**Comment by nilsteampassnet** [comment]
And ?

You have checked all the messages after?
What is your status?

**Comment by Nathu2018** [comment]
IT tried this mentioned there but it doesn’t help me out

Php.erro show

Undefined property: stdClass::$nright in C:\wamp64\www\TeamPass\includes\libraries\Tree\NestedTree\NestedTree.php on line 422

ND

**Comment by Nathu2018** [comment]
Hi

After new installation I had tried to login with admin as well as local user or AD user I can`t see any under manage folder or manage user.

[cid:image005.jpg@01D3C2A6.AC46FF10]

[cid:image006.jpg@01D3C2A6.AC46FF10]

[cid:image007.jpg@01D3C2A6.AC46FF10]

**Comment by nilsteampassnet** [comment]
Can you please upload your images from Github. They are not added by email.

**Comment by jakubmuransky** [comment]
Hello, same problem. Empty users&folders page but roles are there. I checked URLs - ok. 
Updatet from 2.1.26 to newest. Upgrade ended with no problems. Server running on ubuntu - apache2

**Comment by rferreira976** [comment]
> Hello guys,
> 
> I encountered the same issue, and it was solved by following what Nil commented in the issue #1905 : by replace http by https in the config page of TeamPass !
> 
> Don't know if you already set this, but I hope you'll get it working.

**Thank you very much!!!** 

This solved my blank page issue (User/Folder)

I'm using version 2.1.27.36, running in docker container

**Comment by wiljunin** [comment]
Oi amigos,

Estou enfrentando o mesmo problema do lukek-imm. Aparentemente tudo está funcionando ok, consigo ver todas as senhas, grupos e etc. Os meus usuarios conseguem se logar, em seus papeis corretamente. Porém eu como administrador, não consigo visualizar nenhum dos usuários e grupos de usuários no item gerenciamento de usuário.
Meu ambiente é: SLES 15 SP1 + PHP 7.2.5.

Quando abre a webconsole e clico em Network, ao carregar a referida pagina percebo dois erros no qual envio em anexo. 

![Erro-Teampass2](https://user-images.githubusercontent.com/34101245/78183957-1d351080-743f-11ea-98c0-d08e0078c69f.png)
![Erros-Teampass](https://user-images.githubusercontent.com/34101245/78183967-1efed400-743f-11ea-8202-87bf2243972a.png)
![Erro-teampass4](https://user-images.githubusercontent.com/34101245/78183970-1f976a80-743f-11ea-8bd7-8deb317d1bf0.png)
![Erro-teampass3](https://user-images.githubusercontent.com/34101245/78183974-20300100-743f-11ea-87ad-df44ad36624c.png)

**Comment by wiljunin** [comment]
up

**Comment by wiljunin** [comment]
### Steps to reproduce
1. Login in teampass
2. Click my profile
3. Error

### Expected behaviour
Tell us what should happen


### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**: Linux zabbixdb2 4.12.14-197.21-default #1 SMP Mon Oct 7 12:41:58 UTC 2019 (8ef2efd) x86_64

**Web server:** Apache

**Database:** 5.5.5-10.2.15-MariaDB

**PHP version:** 7.2.5

**Teampass version:** 2.1.27.36

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '1',
'show_last_items' => '1',
'enable_pf_feature' => '0',
'log_connections' => '1',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd/m/Y',
'duplicate_folder' => '0',
'item_duplicate_in_same_folder' => '0',
'duplicate_item' => '0',
'number_of_used_pw' => '3',
'manager_edit' => '1',
'cpassman_dir' => '/data/www/htdocs/teampass',
'cpassman_url' => 'https://<anonym_url>/teampass
'favicon' => 'https://<anonym_url>/teampass/favicon.ico',
'path_to_upload_folder' => '/data/www/htdocs/teampass/upload',
'url_to_upload_folder' => 'https://<anonym_url>/teampass/upload',
'path_to_files_folder' => '/data/www/htdocs/teampass/files',
'url_to_files_folder' => 'https://<anonym_url>/teampass/files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'maintenance_mode' => '0',
'enable_sts' => '0',
'encryptClientServer' => '1',
'cpassman_version' => '2.1.27',
'ldap_mode' => '0',
'ldap_type' => '0',
'ldap_suffix' => '0',
'ldap_domain_dn' => '0',
'ldap_domain_controler' => '0',
'ldap_user_attribute' => '0',
'ldap_ssl' => '0',
'ldap_tls' => '0',
'ldap_elusers' => '0',
'ldap_search_base' => '0',
'richtext' => '0',
'allow_print' => '0',
'roles_allowed_to_print' => '1',
'show_description' => '1',
'anyone_can_modify' => '0',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '5',
'utf8_enabled' => '1',
'restricted_to' => '0',
'restricted_to_roles' => '0',
'enable_send_email_on_user_login' => '1',
'enable_user_can_create_folders' => '0',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '0',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '0',
'custom_logo' => 'https://<anonnymous/_comum/img/sgp_topo_horizontal.png',
'custom_login_text' => 'XXX',
'default_language' => 'portuguese_br',
'send_stats' => '0',
'send_statistics_items' => 'stat_country;stat_users;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_fav;stat_pf;',
'send_stats_time' => '1506367147',
'get_tp_info' => '1',
'send_mail_on_user_login' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '0',
'personal_saltkey_cookie_duration' => '31',
'email_smtp_server' => 'smtp.cjf.local',
'email_smtp_auth' => '0',
'email_auth_username' => '',
'email_auth_pwd' => '<removed>'
'email_port' => '',
'email_security' => '',
'email_server_url' => 'http://<anonnymous>/teampass',
'email_from' => 'sesinf@xxx.br',
'email_from_name' => 'SUTEC Teampass ',
'pwd_maximum_length' => '60',
'google_authentication' => '0',
'delay_item_edition' => '0',
'allow_import' => '1',
'proxy_ip' => '',
'proxy_port' => '',
'upload_maxfilesize' => '10mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '800',
'upload_imageresize_height' => '600',
'upload_imageresize_quality' => '90',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass for ChangeMe',
'api' => '0',
'subfolder_rights_as_parent' => '0',
'show_only_accessible_folders' => '0',
'enable_suggestion' => '0',
'otv_expiration_period' => '7',
'default_session_expiration_time' => '20',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => '0',
'bck_script_path' => '/data/www/htdocs/teampass/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '0',
'syslog_host' => 'localhost',
'syslog_port' => '514',
'manager_move_item' => '0',
'create_item_without_password' => '1',
'otv_is_enabled' => '0',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '0',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'America/Sao_Paulo',
'enable_attachment_encryption' => '1',
'can_create_root_folder' => '1',
'bck_script_passkey' => '<removed>'
'teampass_version' => '2.1.27',
'personal_saltkey_security_level' => '0',
'ldap_new_user_is_administrated_by' => '0',
'ldap_port' => '389',
'offline_key_level' => '0',
'enable_http_request_login' => '0',
'admin_2fa_required' => '1',
'ldap_and_local_authentication' => '0',
'secure_display_image' => '1',
'upload_zero_byte_file' => '0',
'upload_all_extensions_file' => '0',
);

```

**Updated from an older Teampass or fresh install:**

### Client configuration

**Browser:** Firefox - 72.0

**Operating system:** OS X - 32bits

### Logs

#### Web server error log
```
Constant COST already defined - /srv/www/htdocs/teampass/includes/config/settings.php (19)
```

#### Teampass 10 last system errors
```
 * 06/12/2018 19:20:10 - Query: INSERT INTO `teampass_items` (`label`,`description`,`pw`,`pw_iv`,`email`,`url`,`id_tree`,`login`,`inactif`,`restricted_to`,`perso`,`anyone_can_modify`,`complexity_level`) VALUES ('teste', '', '', '', '', '', '37', '', '0', '', '0', '0', NULL)<br />Error: Column 'complexity_level' cannot be null<br />@ /teampass/sources/items.queries.php
 * 06/12/2018 19:10:15 - Query: INSERT INTO `teampass_items` (`label`,`description`,`pw`,`pw_iv`,`email`,`url`,`id_tree`,`login`,`inactif`,`restricted_to`,`perso`,`anyone_can_modify`,`complexity_level`) VALUES ('542525', '', '', '', '', '', '37', '5546654654654', '0', '', '0', '0', NULL)<br />Error: Column 'complexity_level' cannot be null<br />@ /teampass/sources/items.queries.php
 * 06/12/2018 19:09:51 - Query: INSERT INTO `teampass_items` (`label`,`description`,`pw`,`pw_iv`,`email`,`url`,`id_tree`,`login`,`inactif`,`restricted_to`,`perso`,`anyone_can_modify`,`complexity_level`) VALUES ('teste', '', '', '', '', '', '37', '', '0', '', '0', '0', NULL)<br />Error: Column 'complexity_level' cannot be null<br />@ /teampass/sources/items.queries.php
 * 06/12/2018 19:09:02 - Query: INSERT INTO `teampass_items` (`label`,`description`,`pw`,`pw_iv`,`email`,`url`,`id_tree`,`login`,`inactif`,`restricted_to`,`perso`,`anyone_can_modify`,`complexity_level`) VALUES ('teste', '', '', '', '', '', '37', '', '0', '', '0', '0', NULL)<br />Error: Column 'complexity_level' cannot be null<br />@ /teampass/sources/items.queries.php
 * 06/12/2018 19:08:49 - Query: INSERT INTO `teampass_items` (`label`,`description`,`pw`,`pw_iv`,`email`,`url`,`id_tree`,`login`,`inactif`,`restricted_to`,`perso`,`anyone_can_modify`,`complexity_level`) VALUES ('teste', '', '', '', '', '', '37', '', '0', '', '0', '0', NULL)<br />Error: Column 'complexity_level' cannot be null<br />@ /teampass/sources/items.queries.php
 * 06/12/2018 19:00:29 - Query: INSERT INTO `teampass_items` (`label`,`description`,`pw`,`pw_iv`,`email`,`url`,`id_tree`,`login`,`inactif`,`restricted_to`,`perso`,`anyone_can_modify`,`complexity_level`) VALUES ('Adobe Acrobat Standart XI', '', 'def502000d3511f87604a9de37d7d1e2942eb93b7d98edb5092ec089ee8842a5181c605a2b8aebdaaa55bac4c623b4f9bfeb210afad59ac159cf2bea7943b34bfdfe5bafdd09bb1644161760f9bcf0ebdeffdb3069654600ede33808c9a5', '', '', 'https://adobeid-na1.services.adobe.com/renga-idprovider/pages/login?callback=https%3A%2F%2Fims-na1.adobelogin.com%2Fims%2Fadobeid%2FSapLws1%2FAdobeID%2Fcode%3Fredirect_uri%3Dhttps%253A%252F%252Flicensing.adobe.com%252Fsap%2528bD1lbiZjPTAwMw%253D%253D%2529%252Fbc%252Fbsp%252Fsap%252Fzavllogin%252Flogin.htm%253Fsap-language%253DEN&client_id=SapLws1&scope=openid%2CAdobeID&denied_callback=https%3A%2F%2Fims-na1.adobelogin.com%2Fims%2Fdenied%2FSapLws1%3Fredirect_uri%3Dhttps%253A%252F%252Flicensing.adobe.com%252Fsap%2528bD1lbiZjPTAwMw%253D%253D%2529%252Fbc%252Fbsp%252Fsap%252Fzavllogin%252Flogin.htm%253Fsap-language%253DEN%26response_type%3Dcode&display=web_v2&relay=7268c1cf-65f8-428e-a41e-2b01214e32b1&locale=en_US&flow_type=code&dc=true&ctx_id=ctx_saplws1&idp_flow_type=login', '37', 'seate@cjf.jus.br', '0', '', '0', '0', 55)<br />Error: Data too long for column 'url' at row 1<br />@ /teampass/sources/items.queries.php
 * 06/12/2018 18:58:58 - Query: INSERT INTO `teampass_items` (`label`,`description`,`pw`,`pw_iv`,`email`,`url`,`id_tree`,`login`,`inactif`,`restricted_to`,`perso`,`anyone_can_modify`,`complexity_level`) VALUES ('Adobe Acrobat Standard XI', '', 'def50200aea4fa080e4b8a1cb8afa336e942195085eb14055b30bc0f154ae2c5f350fa8c702045cd1cbd1100cd506bb76c66be24a72e34b948f059bcc0a8eefa3365720fec7fbb8f427d2a15cbf73e256034c466f33a7ca7b9ebda72282c', '', '', 'https://adobeid-na1.services.adobe.com/renga-idprovider/pages/login?callback=https%3A%2F%2Fims-na1.adobelogin.com%2Fims%2Fadobeid%2FSapLws1%2FAdobeID%2Fcode%3Fredirect_uri%3Dhttps%253A%252F%252Flicensing.adobe.com%252Fsap%2528bD1lbiZjPTAwMw%253D%253D%2529%252Fbc%252Fbsp%252Fsap%252Fzavllogin%252Flogin.htm%253Fsap-language%253DEN&client_id=SapLws1&scope=openid%2CAdobeID&denied_callback=https%3A%2F%2Fims-na1.adobelogin.com%2Fims%2Fdenied%2FSapLws1%3Fredirect_uri%3Dhttps%253A%252F%252Flicensing.adobe.com%252Fsap%2528bD1lbiZjPTAwMw%253D%253D%2529%252Fbc%252Fbsp%252Fsap%252Fzavllogin%252Flogin.htm%253Fsap-language%253DEN%26response_type%3Dcode&display=web_v2&relay=7268c1cf-65f8-428e-a41e-2b01214e32b1&locale=en_US&flow_type=code&dc=true&ctx_id=ctx_saplws1&idp_flow_type=login', '37', 'seate@cjf.jus.br', '0', '', '0', '0', 55)<br />Error: Data too long for column 'url' at row 1<br />@ /teampass/sources/items.queries.php
 * 22/08/2018 17:45:09 - Query: INSERT INTO `teampass_items` (`label`,`description`,`pw`,`pw_iv`,`email`,`url`,`id_tree`,`login`,`inactif`,`restricted_to`,`perso`,`anyone_can_modify`,`complexity_level`) VALUES ('svc_varonis_admin [ Conta de serviço do Varonis]', '', '', '', '', '', '34', '', '0', '', '0', '0', NULL)<br />Error: Column 'complexity_level' cannot be null<br />@ /teampass/sources/items.queries.php
 * 18/04/2018 18:55:21 - Query: INSERT INTO `teampass_items` (`label`,`description`,`pw`,`pw_iv`,`email`,`url`,`id_tree`,`login`,`inactif`,`restricted_to`,`perso`,`anyone_can_modify`,`complexity_level`) VALUES ('Controladora Wireless', 'usuario: admin<br />senha : Cjf@1!!**wifi', '', '', '', '', '38', '', '0', '', '0', '0', NULL)<br />Error: Column 'complexity_level' cannot be null<br />@ /teampass/sources/items.queries.php
 * 13/04/2018 20:30:02 - Query: INSERT INTO `teampass_items` (`label`,`description`,`pw`,`pw_iv`,`email`,`url`,`id_tree`,`login`,`inactif`,`restricted_to`,`perso`,`anyone_can_modify`,`complexity_level`) VALUES ('vCenter', '', '', '', '', '', '40', '', '0', '', '0', '0', NULL)<br />Error: Column 'complexity_level' cannot be null<br />@ /teampass/sources/items.queries.php
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by tmanok** [comment]
Following the suggestion from user @phess1 "On the config page all my URLs are using the IP address. When I access the server via server name, I experience this issue. When I access it via IP I do not have the issue." the server began displaying folders under Manage Folders and users under Manage Users. Thanks Phess1! I was connecting via IP internally but it was set to a domain name...

**Comment by belovandrey** [comment]
I had the same problem when running through chrome and IE, but there was no problem in Safari.
I tried all of the above, I realized that most likely the question is in the SSL. I checked that https was everywhere, I almost despaired, but the last attempt - to clear the SSL cache in the browser solved the situation.
before that I also tried to increase maxQueryString, it did not help.
