### ISSUE TITLE
Offline mode personal folder password empty

### ISSUE THREAD

**Issue by lduriez** [nilsteampassnet/TeamPass#2215]
### Steps to reproduce
1. Export personal folder with offline mode

### Expected behaviour
After enter the "decryption key", when "decrypt" the passwords we should see them

### Actual behaviour
But all of them are blank/empty, while on online mode we can see them.

### Server configuration
**Operating system**:
Debian Jessie 8.10
**Web server:**
Apache/2.4.10
**Database:**
MySQL 5.5.59
**PHP version:**
5.6.33-0
**Teampass version:** 
2.1.27.11
**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Mozilla Firefox 59.0.2 & Google Chrome 65.0.3325.181
**Operating system:**
Ubuntu Xenial 16.04
#### Web server error log
```
Insert your webserver log here
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
Insert the log here and especially the answer of the query that failed.
```

**Comment by nilsteampassnet** [comment]
I cannot reproduce.

There have been a repackaging of 2.1.27.11. Perhaps could you over-write current files with latest package.
Because issue #2096  was fixed  lately in 2.1.27.11

**Comment by nilsteampassnet** [comment]
Please reopen on need

**Comment by lduriez** [comment]
I tried what you suggest but the problem is still here.

Is it because of the personal salt key which encryt the personal folder and so when we use offline mode these are 2 encryptions (personal salt key + offline saltkey) ?
