### ISSUE TITLE
2fa ignored upon sign-in after upgrade to 2.1.27.26

### ISSUE THREAD

**Issue by CrazyHorse019** [nilsteampassnet/TeamPass#2463]
### Steps to reproduce
1. Upgraded to 2.1.27.26
2. 2FA is enabled via admin account
3. 2FA is ignored upon sign in for all users

### Expected behaviour
on log in page username, password and 2fa code all required to access account

### Actual behaviour
username and password sufficient to log in to accounts even with the 2fa filled with zero or wrong information

### Server configuration
**Operating system**:
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

**Web server:**
nginx

**Database:**
mariadb

**PHP version:**
PHP 7.0.18-1+deb.sury.org~trusty+1 (cli) (built: Apr 11 2017 15:08:38) ( NTS )

**Teampass version:** 
2.1.27.26

**Teampass configuration file:**
```
'email_server_url' => '',
    'email_from' => '****@****.com',
    'email_from_name' => 'teampass',
    'pwd_maximum_length' => '40',
    'google_authentication' => '1',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass',
    'api' => '0',
    'subfolder_rights_as_parent' => '1',
    'show_only_accessible_folders' => '1',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => 'person',
    'bck_script_path' => '/data/nginx/backups',
    'bck_script_filename' => 'bck_cpassman',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'enable_attachment_encryption' => '1',
    'ldap_usergroup' => 'cn=****,ou=groups,dc=****,dc=net',
    'ldap_bind_dn' => 'uid=****,ou=system,dc=****,dc=net',
    'ldap_bind_passwd' => '*****',
    'saltkey_ante_2127' => 'none',
    'teampass_version' => '2.1.27',
    'migration_to_2127' => 'done',
    'timezone' => 'UTC',
    'personal_saltkey_security_level' => '0',
    'ldap_new_user_is_administrated_by' => '0',
    'ldap_port' => '389',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'admin_2fa_required' => '1',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'files_with_defuse' => 'done',
    );
```

### Client configuration
**Browser:**
Chrome

**Operating system:**
macOS mojave

#### Web server error log
```
**.**.**.** - - [05/Nov/2018:12:32:30 +0000] "POST /sources/items.queries.php HTTP/2.0" 200 2636 "https://teampass.*****..net/index.php?page=items" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
**.**.**.**  - - [05/Nov/2018:12:32:30 +0000] "POST /sources/items.queries.php HTTP/2.0" 200 7969 "https://teampass.*****..net/index.php?page=items" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
**.**.**.**  - - [05/Nov/2018:12:32:32 +0000] "POST /sources/items.queries.php HTTP/2.0" 200 668 "https://teampass.*****.net/index.php?page=items" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
**.**.**.**  - - [05/Nov/2018:12:32:32 +0000] "POST /sources/items.queries.php HTTP/2.0" 200 171 "https://teampass.*****..net/index.php?page=items" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
**.**.**.**  - - [05/Nov/2018:12:32:32 +0000] "POST /sources/main.queries.php HTTP/2.0" 200 301 "https://teampass.*****..net/index.php?page=items" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
**.**.**.** - - [05/Nov/2018:12:32:34 +0000] "POST /sources/items.logs.php HTTP/2.0" 200 20 "https://teampass.*****..net/index.php?page=items" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
**.**.**.**  - - [05/Nov/2018:12:32:35 +0000] "POST /sources/items.logs.php HTTP/2.0" 200 20 "https://teampass.*****.net/index.php?page=items" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)

[teampass.zip](https://github.com/nilsteampassnet/TeamPass/files/2548319/teampass.zip)

**Comment by nilsteampassnet** [comment]
This has been fixed in release 2.1.27.27

**Comment by CrazyHorse019** [comment]
Hi Nils, 

I have upgraded this to version 2.1.27.27 and issue still persists. 2FA is getting ignored upon login.

**Comment by CrazyHorse019** [comment]
Hi, this 2FA issue is resolved in 2.1.27.28 - thanks
