### ISSUE TITLE
LDAP Password change: old PW still valid

### ISSUE THREAD

**Issue by dkrey** [nilsteampassnet/TeamPass#2511]
Hi,
it seems like Teampass uses some sort of local cache for the LDAP Password verification. Otherwise I have no idea how teampass still manages to verifiy the old password. Other PHP applications on the same servers (ie nextcloud) work fine with the same configuration.
It also worked fine in teampass for the last years. But since I upgraded from 2.1.27.15 to 2.1.27.30 it doesn't work anymore.

### Steps to reproduce
1. Change the password on the LDAP Directory
2. Try to login with the new password

### Expected behaviour
The new password should be accepted

### Actual behaviour
The old password is still valid, the new one is denied

### Server configuration
**Operating system**: Linux 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 07:15:04 PDT 2017 x86_64

**Web server:** nginx/1.12.2

**Database:** 5.5.5-10.2.19-MariaDB

**PHP version:** 7.2.12

**Teampass version:** 2.1.27.30

**Teampass configuration file:**
```
'max_latest_items' => '10',
'enable_favourites' => '1',
'show_last_items' => '1',
'enable_pf_feature' => '1',
'log_connections' => '1',
'log_accessed' => '1',
'time_format' => 'H:i:s',
'date_format' => 'd/m/Y',
'duplicate_folder' => '1',
'item_duplicate_in_same_folder' => '1',
'duplicate_item' => '1',
'number_of_used_pw' => '3',
'manager_edit' => '1',
'cpassman_dir' => '/ado/sw/apps/www/html/teampass',
'cpassman_url' => 'https://<anonym_url>/teampass
'favicon' => 'https://<anonym_url>/teampass/favicon.ico',
'path_to_upload_folder' => '/ado/sw/apps/www/html/teampass/upload',
'url_to_upload_folder' => 'https://<anonym_url>/teampass/upload',
'path_to_files_folder' => '/ado/sw/apps/www/html/teampass/files',
'url_to_files_folder' => 'https://<anonym_url>/teampass/files',
'activate_expiration' => '0',
'pw_life_duration' => '0',
'maintenance_mode' => '0',
'enable_sts' => '0',
'encryptClientServer' => '1',
'cpassman_version' => '2.1.27',
'ldap_mode' => '1',
'ldap_type' => 'posix-search',
'ldap_suffix' => '',
'ldap_domain_dn' => '0',
'ldap_domain_controler' => '<removed but valid>',
'ldap_user_attribute' => 'uid',
'ldap_ssl' => '1',
'ldap_tls' => '0',
'ldap_elusers' => '0',
'ldap_search_base' => 'ou=people,dc=adm',
'richtext' => '0',
'allow_print' => '1',
'roles_allowed_to_print' => '1',
'show_description' => '1',
'anyone_can_modify' => '0',
'anyone_can_modify_bydefault' => '0',
'nb_bad_authentication' => '0',
'utf8_enabled' => '1',
'restricted_to' => '0',
'restricted_to_roles' => '0',
'enable_send_email_on_user_login' => '0',
'enable_user_can_create_folders' => '0',
'insert_manual_entry_item_history' => '0',
'enable_kb' => '0',
'enable_email_notification_on_item_shown' => '0',
'enable_email_notification_on_user_pw_change' => '0',
'custom_logo' => 'https://<anonym_url>/teampass/logo.png',
'custom_login_text' => '',
'default_language' => 'german',
'send_stats' => '0',
'send_statistics_items' => '',
'send_stats_time' => '1499691385',
'get_tp_info' => '0',
'send_mail_on_user_login' => '0',
'nb_items_by_query' => 'auto',
'enable_delete_after_consultation' => '0',
'enable_personal_saltkey_cookie' => '1',
'personal_saltkey_cookie_duration' => '9999',
'email_smtp_server' => 'localhost',
'email_smtp_auth' => '',
'email_auth_username' => 'dkrey',
'email_auth_pwd' => '<removed>'
'email_port' => '25',
'email_security' => '',
'email_server_url' => 'https://<anonym_url>/teampass/',
'email_from' => '<removed>',
'email_from_name' => 'Teampass',
'pwd_maximum_length' => '64',
'google_authentication' => '0',
'delay_item_edition' => '0',
'allow_import' => '1',
'proxy_ip' => '',
'proxy_port' => '',
'upload_maxfilesize' => '10mb',
'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
'upload_imagesext' => 'jpg,jpeg,gif,png',
'upload_pkgext' => '7z,rar,tar,zip',
'upload_otherext' => 'sql,xml',
'upload_imageresize_options' => '1',
'upload_imageresize_width' => '800',
'upload_imageresize_height' => '600',
'upload_imageresize_quality' => '90',
'use_md5_password_as_salt' => '0',
'ga_website_name' => 'TeamPass for ChangeMe',
'api' => '0',
'subfolder_rights_as_parent' => '1',
'show_only_accessible_folders' => '1',
'enable_suggestion' => '0',
'otv_expiration_period' => '7',
'default_session_expiration_time' => '1200',
'duo' => '0',
'enable_server_password_change' => '0',
'ldap_object_class' => 'posixAccount',
'bck_script_path' => '/ado/sw/apps/www/html/teampass/backups',
'bck_script_filename' => 'bck_teampass',
'syslog_enable' => '0',
'syslog_host' => 'localhost',
'syslog_port' => '514',
'manager_move_item' => '0',
'create_item_without_password' => '0',
'otv_is_enabled' => '0',
'agses_authentication_enabled' => '0',
'item_extra_fields' => '0',
'saltkey_ante_2127' => 'none',
'migration_to_2127' => 'done',
'files_with_defuse' => 'done',
'timezone' => 'Europe/Berlin',
'ldap_bind_dn' => 'cn=agent,dc=adm',
'ldap_bind_passwd' => '<removed>'
'ldap_port' => '636',
'copy_to_clipboard_small_icons' => '1',
'ldap_usergroup' => 'ou=group,dc=adm',
'teampass_version' => '2.1.27',
'personal_saltkey_security_level' => '0',
'ldap_new_user_is_administrated_by' => '0',
'offline_key_level' => '0',
'enable_http_request_login' => '0',
'ldap_and_local_authentication' => '1',
'secure_display_image' => '1',
'upload_zero_byte_file' => '0',
'upload_all_extensions_file' => '0',
'ldap_new_user_role' => '1',
'admin_2fa_required' => '1',
);
```

**Updated from an older Teampass 2.1.27.29**

### Client configuration

**Browser:** Firefox - 64.0

**Operating system:** Windows - 64bits

#### Web server error log
```
Constant COST already defined - /ado/sw/apps/www/html/teampass/includes/config/settings.php (19)
```

#### Teampass 10 last system errors
```
unrelated errors from a year ago
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
[{value: "false", user_admin: "", initial_url: "", error: "", pwd_attempts: "2"}]
0: {value: "false", user_admin: "", initial_url: "", error: "", pwd_attempts: "2"}
error: ""
initial_url: ""
pwd_attempts: "2"
user_admin: ""
value: "false"
```

#### Log from the duo.debug.txt with old password
```
Content of data sent '<long string>'
Starting authentication of 'dkrey'
LDAP status: 1
USer exists: 1
Proceed with Ident: 1
User's password verified: 1
User's token: <a token>
Preparing to identify the user rights


----
Identified : <a 10 char string>
```

#### Log from the duo.debug.txt with new password
```
Content of data sent '<long string>'
Starting authentication of 'dkrey'
LDAP status: 1
USer exists: 1
Proceed with Ident: 1
User's password verified:


----
Identified : false
```

#### Log from the ldap.debug.txt
```
Get all LDAP params :
mode : 1
type : posix-search
base_dn : 0
search_base : ou=people,dc=adm
bind_dn : cn=agent,dc=adm
bind_passwd : <removed>
user_attribute : uid
account_suffix :
domain_controllers : <valid ldap ip>
ad_port : 636
use_ssl : 1
use_tls : 0
*********

LDAP URIs : ldaps://<valid ldap ip>
LDAP connection : Connected
LDAP bind : Bound
Search filter : (&(uid=dkrey)(objectClass=posixAccount))
Results : Array
(
    [count] => 1
    [0] => Array
        (
            [sn] => Array
                (
                    [count] => 1
                    [0] => dkrey
                )

            [0] => sn
            [count] => 1
            [dn] => cn=dkrey,ou=people,dc=adm
        )

)

User was found. cn=dkrey,ou=people,dc=adm\nSearch groups appartenance : ou=people,dc=adm
Results : Array
(
    [count] => 0
)

Group was found : false
```

**Comment by dkrey** [comment]
Here's some more insight:
Inside the admin settings, the ldap check works as expected: the old PW is invalid and the new one is valid. So this issue seems to affect only the login.

#### LDAP Check from the Admin Settings: old PW
```
LDAP URIs : <valid_ip>
LDAP connection : Connected
DN : cn=agent,dc=adm -- <removed>
LDAP bind : Bound
Search filter (group): memberUid=dkrey
Results : Array
(
[count] => 0
)

Find user in Group:
Search filter : (&(uid=dkrey)(objectClass=posixAccount))
Results : Array
(
[count] => 1
[0] => Array
(
[sn] => Array
(
[count] => 1
[0] => dkrey
)

[0] => sn
[uid] => Array
(
[count] => 1
[0] => dkrey
)

[1] => uid
[count] => 2
[dn] => cn=dkrey,ou=people,dc=adm
)

)

Error - Cannot connect user!
```

#### LDAP Check from the Admin Settings: new PW
```
LDAP URIs : <valid_ip>
LDAP connection : Connected
DN : cn=agent,dc=adm -- <removed>
LDAP bind : Bound
Search filter (group): memberUid=dkrey
Results : Array
(
[count] => 0
)

Find user in Group:
Search filter : (&(uid=dkrey)(objectClass=posixAccount))
Results : Array
(
[count] => 1
[0] => Array
(
[sn] => Array
(
[count] => 1
[0] => dkrey
)

[0] => sn
[uid] => Array
(
[count] => 1
[0] => dkrey
)

[1] => uid
[count] => 2
[dn] => cn=dkrey,ou=people,dc=adm
)

)

Successfully connected
```

**Comment by nilsteampassnet** [comment]
Yes it is a problem that I have identified a long time ago on 2.1.27 since adding several possibilities to LDAP.
It is fixed in the future release of Teampass 3.x.
But not reported in branch 2.x. I will try to do it soon.

**Comment by dkrey** [comment]
Alright, thanks for the info.

**Comment by dkrey** [comment]
I've just checked v 1.27.33, but this issue still exists: my old password is still valid, Browser cache wiped and cookies deleted.

**Comment by nilsteampassnet** [comment]
I don't understand as this version includes the fix.
Performing new tests just now, I cannot reproduce it anymore.
Perhaps is there something wrong in this package (bad merge) ... i need to check.

**Comment by dkrey** [comment]
I finally found the time to dig deeper into this issue. It turned out that I had to remove the group-filter for this to work. As I only allow local users, this isn't a problem for me.
