### ISSUE TITLE
Login not possible after fresh install

### ISSUE THREAD

**Issue by relkai** [nilsteampassnet/TeamPass#2963]
### Steps to reproduce
1. git clone https://github.com/nilsteampassnet/TeamPass.git
2. Perform all steps in the install wizard
3. Trying to login with the admin account created during installation

### Expected behaviour
Successful login into TeamPass

### Actual behaviour
The "In progress" bar at the top of the page spins forever.
In the Apache logs the error from the logs section below is being displayed.

Looking at the function `mfa_auth_requested` it seems, the first parameter is the value `fonction_id` from the users table. The value for the "admin" user is set to NULL (so not a string as expected from this function).
If I change it in the database to e.g. "1" I'm getting an error about wrong credentials instead.

### Server configuration
**Operating system**:
Ubuntu 20.04.3 LTS

**Web server:**
Apache 2.4.41-4ubuntu3.4

**Database:**
MariaDB-10.3.31

**PHP version:**
7.4.3

**Teampass version:** 
3.0.0.9

**Teampass configuration file:**

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.
```global $SETTINGS;
$SETTINGS = array (
    'max_latest_items' => '10',
    'enable_favourites' => '1',
    'show_last_items' => '1',
    'enable_pf_feature' => '0',
    'log_connections' => '1',
    'log_accessed' => '1',
    'time_format' => 'H:i:s',
    'date_format' => 'd/m/Y',
    'duplicate_folder' => '0',
    'item_duplicate_in_same_folder' => '0',
    'duplicate_item' => '0',
    'number_of_used_pw' => '3',
    'manager_edit' => '1',
    'cpassman_dir' => '/var/www/html/teampass',
    'cpassman_url' => 'http://xxx/teampass',
    'favicon' => 'http://xxx/teampass/favicon.ico',
    'path_to_upload_folder' => '/var/www/html/teampass/upload',
    'path_to_files_folder' => '/var/www/html/teampass/files',
    'url_to_files_folder' => 'http://xxx/teampass/files',
    'activate_expiration' => '0',
    'pw_life_duration' => '0',
    'maintenance_mode' => '1',
    'enable_sts' => '0',
    'encryptClientServer' => '1',
    'cpassman_version' => '3.0.0.9',
    'ldap_mode' => '0',
    'ldap_type' => '0',
    'ldap_suffix' => '0',
    'ldap_domain_dn' => '0',
    'ldap_domain_controler' => '0',
    'ldap_user_attribute' => '0',
    'ldap_ssl' => '0',
    'ldap_tls' => '0',
    'ldap_elusers' => '0',
    'ldap_search_base' => '0',
    'ldap_port' => '389',
    'richtext' => '0',
    'allow_print' => '0',
    'roles_allowed_to_print' => '0',
    'show_description' => '1',
    'anyone_can_modify' => '0',
    'anyone_can_modify_bydefault' => '0',
    'nb_bad_authentication' => '0',
    'utf8_enabled' => '1',
    'restricted_to' => '0',
    'restricted_to_roles' => '0',
    'enable_send_email_on_user_login' => '0',
    'enable_user_can_create_folders' => '0',
    'insert_manual_entry_item_history' => '0',
    'enable_kb' => '0',
    'enable_email_notification_on_item_shown' => '0',
    'enable_email_notification_on_user_pw_change' => '0',
    'custom_logo' => '',
    'custom_login_text' => '',
    'default_language' => 'english',
    'send_stats' => '0',
    'send_statistics_items' => 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;',
    'send_stats_time' => '1628002975',
    'get_tp_info' => '1',
    'send_mail_on_user_login' => '0',
    'sending_emails' => '0',
    'nb_items_by_query' => 'auto',
    'enable_delete_after_consultation' => '0',
    'enable_personal_saltkey_cookie' => '0',
    'personal_saltkey_cookie_duration' => '31',
    'email_smtp_server' => '',
    'email_smtp_auth' => '',
    'email_auth_username' => '',
    'email_auth_pwd' => '',
    'email_port' => '',
    'email_security' => '',
    'email_server_url' => '',
    'email_from' => '',
    'email_from_name' => '',
    'pwd_maximum_length' => '40',
    'google_authentication' => '0',
    'delay_item_edition' => '0',
    'allow_import' => '0',
    'proxy_ip' => '',
    'proxy_port' => '',
    'upload_maxfilesize' => '10mb',
    'upload_docext' => 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx',
    'upload_imagesext' => 'jpg,jpeg,gif,png',
    'upload_pkgext' => '7z,rar,tar,zip',
    'upload_otherext' => 'sql,xml',
    'upload_imageresize_options' => '1',
    'upload_imageresize_width' => '800',
    'upload_imageresize_height' => '600',
    'upload_imageresize_quality' => '90',
    'use_md5_password_as_salt' => '0',
    'ga_website_name' => 'TeamPass for XXX',
    'api' => '0',
    'subfolder_rights_as_parent' => '0',
    'show_only_accessible_folders' => '0',
    'enable_suggestion' => '0',
    'otv_expiration_period' => '7',
    'default_session_expiration_time' => '60',
    'duo' => '0',
    'enable_server_password_change' => '0',
    'ldap_object_class' => '0',
    'bck_script_path' => '/var/www/html/teampass/backups',
    'bck_script_filename' => 'bck_teampass',
    'syslog_enable' => '0',
    'syslog_host' => 'localhost',
    'syslog_port' => '514',
    'manager_move_item' => '0',
    'create_item_without_password' => '0',
    'otv_is_enabled' => '0',
    'agses_authentication_enabled' => '0',
    'item_extra_fields' => '0',
    'saltkey_ante_2127' => 'none',
    'migration_to_2127' => 'done',
    'files_with_defuse' => 'done',
    'timezone' => 'UTC',
    'enable_attachment_encryption' => '1',
    'personal_saltkey_security_level' => '50',
    'ldap_new_user_is_administrated_by' => '0',
    'disable_show_forgot_pwd_link' => '0',
    'offline_key_level' => '0',
    'enable_http_request_login' => '0',
    'ldap_and_local_authentication' => '0',
    'secure_display_image' => '1',
    'upload_zero_byte_file' => '0',
    'upload_all_extensions_file' => '0',
    'bck_script_passkey' => 'XXXXXXXXXXXXXXXXXXXXXXX',
    'admin_2fa_required' => '1',
    'password_overview_delay' => '4',
    'copy_to_clipboard_small_icons' => '1',
    'duo_akey' => '',
    'duo_ikey' => '',
    'duo_skey' => '',
    'duo_host' => '',
    'teampass_version' => '',
    'roles_allowed_to_print_select' => '',
    'clipboard_life_duration' => '30',
    'mfa_for_roles' => '',
);
```

### Client configuration
**Browser:**
Google Chrome 92.0.4515.159

**Operating system:**
Windows 10 build 21H1

#### Web server error log
```
[Fri Sep 03 16:56:39.969142 2021] [php7:error] [pid 246724] [client 10.2.218.185:63807] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to mfa_auth_requested() must be of the type string, bool given, called in /var/www/html/teampass/sources/identify.php on line 1558 and defined in /var/www/html/teampass/sources/main.functions.php:2965\nStack trace:\n#0 /var/www/html/teampass/sources/identify.php(1558): mfa_auth_requested()\n#1 /var/www/html/teampass/sources/identify.php(349): identifyDoInitialChecks()\n#2 /var/www/html/teampass/sources/identify.php(201): identifyUser()\n#3 {main}\n  thrown in /var/www/html/teampass/sources/main.functions.php on line 2965, referer: http://xxx/teampass/index.php
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
POST http://xxx/teampass/sources/identify.php 500 (Internal Server Error)
```

**Comment by nilsteampassnet** [comment]
Confirmed.
Stupid error.

**Comment by nilsteampassnet** [comment]
Should be fixed

**Comment by relkai** [comment]
Thanks a lot for the fix, Nils.
Login is possible now, but I still need to manually set `teampass_users.fonction_id` to the value `1` directly in the database. Otherwise the same error still appears in the Apache logs and the "in progress" banner spinning forever.
To be sure it wasn't a problem on my end, I did another fresh install of the 3.0 branch.

**Comment by lanaparadinha** [comment]
same error here... :(
