### ISSUE TITLE
Installation Errors - Caution 

### ISSUE THREAD

**Issue by tiredofit** [nilsteampassnet/TeamPass#3182]
I am trying to install Teampass 3 (master) into an nginx-php-fpm image that is being used by millions of people around the world, similar to the one you have chosen in your docker-compose. I have specific requirements to utilize this image for the feature set and in return will also provide a working Teampass 3 image for the community (I already do at https://github.com/tiredofit/docker-teampass for the 2.x series.).

When performing the installation we are faced with many errors after the fact.,

### Steps to reproduce
1. Utilize tiredofit/nginx-php-fpm:8.0 as base image, MariaDB 10.6.7
2. Install into `/www/teampass`
3. Go through installation steps - All pass successfully. Place sk in `/www/sk/`
4. **MANUALLY DELETE INSTALL FOLDER AS IT DOES NOT DO IT AUTOMATICALLLY**

### Expected behaviour
- When visiting login screen am presented with: "Caution - **OzKOYhERERFx5XpPm3IdOxect9QEGLzjAcr1BPox6yU1JvFUHnbHnFdluuMM/1NGlc+gnIFaf0PTgvvl7A=="

![image](https://user-images.githubusercontent.com/23528985/170276688-a9af1efc-9526-4b41-92bf-9c2382377709.png)

Upon login: 
- Presented with "Hacking attempt"
- Hard Refresh the page and successfully login

Presented with: **_Cautiion_** yet again:

````caution
Warning: Cannot modify header information - headers already sent by (output started at /www/teampass/includes/language/english.php:1) in /www/teampass/sources/main.functions.php on line 47

Warning: Cannot modify header information - headers already sent by (output started at /www/teampass/includes/language/english.php:1) in /www/teampass/sources/main.functions.php on line 48

Warning: Cannot modify header information - headers already sent by (output started at /www/teampass/includes/language/english.php:1) in /www/teampass/sources/main.queries.php on line 86

Warning: Cannot modify header information - headers already sent by (output started at /www/teampass/includes/language/english.php:1) in /www/teampass/sources/main.queries.php on line 87
kjKOYnNzc3MmQ+q2glPuZDC6CMjrbe/+XLMdMvPDMz+x2xh434sxkZ0JlgttIk1WCCX9u+vluRwh4vx/KtW5bUBmeMZ+nEjcSKxqHefTSRiaB8Uezhj5MKjU
````

When visiting left hand admin sections are presented with similar screens.

When visiting the Users screen am presented with a new popup box that shows the sites name followed by:

`DataTables warning: table id=table-users - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1`

### Server configuration
**Operating system**: Docker / tiredofit/nginx-php-fpm:8.0 (Alpine 3.16)

**Web server:** Nginx 1.22.0

**Database:** MariaDB 10.67

**PHP version:**  PHP 8.0.16

**Teampass version:** master

### Client configuration
**Browser:** Firefox, Chrome

**Operating system:** Linux

** Nginx Configuration: **

````bash
server {

    listen 80;
    root /www/teampass;
    index  index.php;
    ###
    location / {
      try_files $uri $uri/ /index.php?$args;
    }

    location ~ [^/]\.php(/|$) {
      fastcgi_split_path_info ^(.+?\.php)(/.*)$;
      if (!-f $document_root$fastcgi_script_name) {
        return 404;
      }
      include /etc/nginx/nginx.conf.d/php-fpm.conf;
      fastcgi_index index.php;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      include fastcgi_params;
    }

}
````

**Comment by tiredofit** [comment]
Also, if you wish to see it for yourself: You can use my docker image: `tiredofit/teampass:develop` and map `/www/teampass` to an exposed volume..

**Comment by purcaholic** [comment]
Enabling the output buffering in PHP should fix this issue, e.g.
`output_buffering = 4096`

**Comment by bjinthahouse** [comment]
> Enabling the output buffering in PHP should fix this issue, e.g. `output_buffering = 4096`
> 
> I had the same issue and setting the output_buffering directive in the php.ini solved it..

I just stumbled upon this, I already have `output_buffering = 4096` in my php.ini and I am still receiving this error.

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
