### ISSUE TITLE
ignored: "New sub-folders inherit permissions from parent folder"

### ISSUE THREAD

**Issue by Nachtlichtermeer** [nilsteampassnet/TeamPass#3372]
### Steps to reproduce
1. upgrade to latest commit a798c9dc9184b5b14184c93c898d727b6418f1e1
2. create new folder
3. new folder is accessible for all groups of creator

### Expected behaviour
folder should only be accessible for group of parend folder

### Actual behaviour
new folder is accessible for all members of all my groups

### Server configuration
**Operating system**:
Ubuntu 20.04
**Web server:**
Apache 2.4.41
**Database:**
MySQL 8.0.28
**PHP version:**
7.4.3
**Teampass version:** 
3.0.0.20

**Comment by Nachtlichtermeer** [comment]
Diff to commit e0ed8ef4e44144930d4d431b705916caa460e3a0

`-                         if (empty($role) === false) {// && empty($access_level_by_role) === false
+                         if (empty($role) === false && empty($access_level_by_role) === false) {`

the old code works for me

please check that and fix it in the code
thanks

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.

**Comment by Nachtlichtermeer** [comment]
error still persists!
tested with commit 1a564ffd1bbe1723432b7d0ed8aebcba75c0d0be

please reopen issue - i can't

**Comment by Nachtlichtermeer** [comment]
problem still persists with commit aab5b00a426c0d7124469ae3ef891ecd5c3e5a08
i'll open a new ticket :-/
