### ISSUE TITLE
"No Access" not working for existing Roles.

### ISSUE THREAD

**Issue by Simon270920** [nilsteampassnet/TeamPass#3374]
### Steps to reproduce
1. Create a new Role => All Folders are set on "no access" => No Problem
2. Switch one Folder Permission to something else and submit
3. Switch back to "no access" and submit => Settings not saved.

### Expected behaviour
The folder where "no access" is set should not be accessible by the User in the specific role. The "no access" setting should be saved.

### Actual behaviour
As soon as you reload the page the Icon for the Folder Access is switched to "no access". If you want to edit the folder permission, none of the three options is marked. The folder is still writable for all Users in that role. 
![image](https://user-images.githubusercontent.com/114504667/196178360-37f76ece-fed9-44ae-964c-22771abe663a.png)

### Server configuration
**Operating system**:
Ubuntu 20.04
**Web server:**
Apache/2.4.41
**Database:**
10.3.34-MariaDB
**PHP version:**
PHP 7.4.3
**Teampass version:** 
3.0.0.20
**Teampass configuration file:**
[tp.config.txt](https://github.com/nilsteampassnet/TeamPass/files/9800550/tp.config.txt)

**Updated from an older Teampass or fresh install:**
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:**
Chrome 106.0.5249.103
Microsoft Edge 44.18362.449.0
**Operating system:**
Windows 10 
#### Web server error log
No Error

#### Log from the web-browser developer console (CTRL + SHIFT + i)
No Error

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.

**Comment by Simon270920** [comment]
Hi Nils, 
thank you. I updated all the files .. but still get the exact same behaviour.

**Comment by Simon270920** [comment]
> A fix has been committed. Please reopen if needed.

Hi Nils, seems like i cant reopen the Issue. Maybe you notice it that way: @nilsteampassnet 

I downloaded the newest files from today. It seems like the technique behinde the Access Roles is working again (But Only for new Roles, even if you set "no access" again for old roles. I am using a fresh installation so its no problem).
But the Setting Pages still shows no marking for "no access" beeing set.
