### ISSUE TITLE
Restricted to field issue

### ISSUE THREAD

**Issue by ketoraire** [nilsteampassnet/TeamPass#3502]
### Steps to reproduce
1. Create an item
2. Restrict that item to one person (details tab) 
3. Save
4. Open the item in view mode (all good, Restricted to is properly showing that person) 
6. But Reopen the item in edit mode, go to details again and... tada

### Expected behaviour
We should see the list of restricted users

### Actual behaviour
The "restricted to" field is empty, so we can't remove that restriction

### Server configuration
Debian 11
Apache2 2.4+
MariaDB 10.8+
PHP 7.4+
Teampass 3.0.0.22

### Client configuration
**Browser:** Chrome / Firefox / Edge (all in private mode for test purpose) 

**Operating system:** Windows 22h2

#### Web server error log
For somes reasons I don't have any logs in error.log (My server configuration are working)

![image](https://user-images.githubusercontent.com/9216494/214872236-150a12e2-21de-4fde-b122-d6411764e43c.png)

**Comment by whosht** [comment]
+1
Same here (found this while searching as the whole restriction stuff is not working correctly anymore after update von 2.x)

**Comment by nilsteampassnet** [comment]
A fix has been committed.
Please reopen if needed.

**Comment by whosht** [comment]
I updated to 6d6cfcbc687951c2671414ea4983e0bbc50a6730 and still see an empty "Restricted to" field.

**Comment by tommihub** [comment]
Current version loaded 3.0.10.48 and have the same Problems.
