### ISSUE TITLE
Unable to view custom field's content after upgrade

### ISSUE THREAD

**Issue by yong-sheng-03** [nilsteampassnet/TeamPass#3945]
### Steps to reproduce
1. Upgrade Teampass from 3.0.10.46 to 3.0.10.135
2. Open any password item that previously had custom fields filled in
3. 

### Expected behaviour
The custom fields should be filled in with information (as per before the upgrade)

### Actual behaviour
The custom fields are empty (except custom fields which data are encrypted in the database)

### Server configuration
**Operating system**: Ubuntu 20.04.6 LTS

**Web server:** 8.0.34-0ubuntu0.20.04.1

**Database:** MySQL

**PHP version:** 8.2.11

**Teampass version:** 3.0.10.135

**Teampass configuration file:** 
[tp.config.php.txt](https://github.com/nilsteampassnet/TeamPass/files/13362375/tp.config.php.txt)

**Updated from an older Teampass or fresh install:** Updated
PLEASE attach to this issue the file `/includes/config/tp.config.php`.

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10

#### Web server error log
```
No error log
```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
No error log
```

**Comment by yong-sheng-03** [comment]
When logged in as admin, I am also unable to load the users in Users page.

**Log from the web-browser developer console (CTRL + SHIFT + i)**
`
index.php:5417 Access to XMLHttpRequest at 'http://10.0.0.48/includes/language/datatables.english.txt' from origin 'http://10.0.5.164' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
10.0.0.48/includes/language/datatables.english.txt:1 
        
        
       Failed to load resource: net::ERR_FAILED
index.php?page=users:1115 Object
index.php:1 Access to XMLHttpRequest at 'http://10.0.0.48/sources/users.datatable.php?draw=1&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=5&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=6&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=true&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=7&columns%5B7%5D%5Bname%5D=&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=true&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B8%5D%5Bdata%5D=8&columns%5B8%5D%5Bname%5D=&columns%5B8%5D%5Bsearchable%5D=true&columns%5B8%5D%5Borderable%5D=true&columns%5B8%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B8%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=1&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1700039193560' from origin 'http://10.0.5.164' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
10.0.0.48/sources/users.datatable.php?draw=1&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=5&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=6&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=true&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=7&columns%5B7%5D%5Bname%5D=&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=true&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B8%5D%5Bdata%5D=8&columns%5B8%5D%5Bname%5D=&columns%5B8%5D%5Bsearchable%5D=true&columns%5B8%5D%5Borderable%5D=true&columns%5B8%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B8%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=1&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1700039193560:1 
        
        
       Failed to load resource: net::ERR_FAILED
index.php:1 Access to XMLHttpRequest at 'http://10.0.0.48/sources/users.datatable.php?draw=2&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=5&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=6&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=true&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=7&columns%5B7%5D%5Bname%5D=&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=true&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B8%5D%5Bdata%5D=8&columns%5B8%5D%5Bname%5D=&columns%5B8%5D%5Bsearchable%5D=true&columns%5B8%5D%5Borderable%5D=true&columns%5B8%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B8%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=1&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1700039193561' from origin 'http://10.0.5.164' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
10.0.0.48/sources/users.datatable.php?draw=2&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=5&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=6&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=true&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B7%5D%5Bdata%5D=7&columns%5B7%5D%5Bname%5D=&columns%5B7%5D%5Bsearchable%5D=true&columns%5B7%5D%5Borderable%5D=true&columns%5B7%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B7%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B8%5D%5Bdata%5D=8&columns%5B8%5D%5Bname%5D=&columns%5B8%5D%5Bsearchable%5D=true&columns%5B8%5D%5Borderable%5D=true&columns%5B8%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B8%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=1&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1700039193561:1 
        
        
       Failed to load resource: net::ERR_FAILED
`

**Comment by WebxDES** [comment]
I just performed a fresh install and im unable to load any of the tabs other than "Options" and there is multiple UI sections that are missing now. 

![image](https://github.com/nilsteampassnet/TeamPass/assets/104908596/190d7d15-355a-4a8d-9d9b-2f058241315c)

**Comment by nilsteampassnet** [comment]
@yong-sheng-03 
Thank you for reporting.
I have fixed the issue.

@WebxDES 
It seems the issue is related to client.
Please, clear the browser cache (CTRL+F5), and check the files consistency on the server

**Comment by sithius82** [comment]
Hello @nilsteampassnet 
Made a fresh install 1 hour ago. The same issue appeared.
Browsers: Firefox, Chrome, LibreWolf. All of them in the normal mode and incognito. The same issue remains.
Also there is no possibility to turn off maintenance mode because of this issue.
The only way to leave the stuck page (refresh is not helping) - to go to link in the upper left corner with Teampass logo
![tp_install_3](https://github.com/nilsteampassnet/TeamPass/assets/20947948/fd3bce95-0d1a-4c46-a153-1cfdb807cfa9)

**Comment by nilsteampassnet** [comment]
@sithius82 
Please provide all possible logs

**Comment by nilsteampassnet** [comment]
@sithius82 
I could finaly reproduce ... working on it

**Comment by nilsteampassnet** [comment]
@sithius82 
Fix has been committed

**Comment by sithius82** [comment]
Thanks a lot! Confirming it works fine now.

**Comment by yong-sheng-03** [comment]
@nilsteampassnet 
I have tried the latest commit. The custom fields are not empty anymore, but the content is not correct as seen in the picture below.

![image](https://github.com/nilsteampassnet/TeamPass/assets/143984786/f9eb1e09-eefd-4551-8b32-f1152c528a4c)

There are no errors in apache log and browser console log. 

Your help is very much appreciated.

**Comment by nilsteampassnet** [comment]
@yong-sheng-03 
I did a small adaptation in latest commit
Please check

**Comment by yong-sheng-03** [comment]
@nilsteampassnet 

I've just tried with the latest commit. 

Whenever I open an item with custom field with content, the following error is shown. 
![image](https://github.com/nilsteampassnet/TeamPass/assets/143984786/b5b6f3c3-f13f-4e06-a407-a7dab2e4cdb4)

Web Console Error: [error_web_console.log](https://github.com/nilsteampassnet/TeamPass/files/13389722/error_web_console.log)
Apache Error Log: nothing

As for this,
> How do you perform this?

I  generated a new OTP from the users list as an admin. As in the last commit, I was unable to generate new keys when logged as the user itself (the button would not function after I clicked confirm). 

However, I will try to do that in the latest commit and report back with the results.

**Comment by nilsteampassnet** [comment]
@yong-sheng-03 
I really don't understand why you get this error.
The field data seems to be base64 encoded so I just added a base64_decode if indeed the data is base64 encoded.
Can you tell me if the fields were previously defined as encrypted in the database?

**Comment by yong-sheng-03** [comment]
@nilsteampassnet 

Update: The custom fields are working now and are showing the correct data after I have generated new keys while logged in as the user. 

Would generating a new OTP from the admin side generate the same outcome? 

Thanks for all the help previously.

**Comment by nilsteampassnet** [comment]
@yong-sheng-03 
Ok so you mean that the latest commit permitted to see the fields value?

**Comment by yong-sheng-03** [comment]
@nilsteampassnet 
Sorry for the confusion but no I am still unable to view the fields value. When clicking into the items with custom fields, the error is still showing.
![image](https://github.com/nilsteampassnet/TeamPass/assets/143984786/fa67baca-052f-43ca-b170-ea00bb035841)


I've tried generating new keys when logged in as the user itself but I am still getting the same error as above. 

As its past office hours where I am, I would not be able to reply to you until next week but I'll try and get back to you with anything as soon as possible. 

Thanks alot for the help.

**Comment by nilsteampassnet** [comment]
@yong-sheng-03 
Ok no problem
Can you just do one thing for testing purpose, and espacially check if the strings you see are base64 encoded.
Please, do the next:
* copy one of those string
* open https://www.base64decode.org/
* paste and decode
* check if result is a valid value for you

**Comment by yong-sheng-03** [comment]
@nilsteampassnet 

I've done all the steps above and the result do NOT return a valid value.

> also are the value in Chinese characters?

No, all the characters inserted were English only.

**Comment by nilsteampassnet** [comment]
@yong-sheng-03 
How strange, I don't understand the whole logic.
Would it be possible next week to have a screensharing session ?

**Comment by yong-sheng-03** [comment]
@nilsteampassnet 

Apologies for the late response.

I've been looking at the teampass database, and I've noticed something. 

The current latest commit of Teampass seems to be loading the custom fields content for an item from the "teampass_categories_items" table of the database (which has the weird encrypted looking data). 

However, in the "teampass_defuse_passwords" table of the database, it has all the unencryped content of the custom field. 

Is it possible that Teampass is getting the data to put in the custom fields from the wrong table? 

Anyways, if you still need more information, a screen sharing session can definitely be arranged.

Thanks.

**Comment by nilsteampassnet** [comment]
Closed automatically due to inactivity (no response for over 1 year).
