### ISSUE TITLE
Unable to use LDAP in version 3.1.4.4

### ISSUE THREAD

**Issue by DaveWebb2** [nilsteampassnet/TeamPass#4626]
I have a clean installation of 3.1.4.4 and cannot log in using LDAP (Active Directory).  When testing credentials on the LDAP page it quickly returns the message "An error occurred while opening connection to AD server".  There is nothing in the web server logs other than this:

`2025-03-11T09:19:25.4468988Z 127.0.0.1 -  11/Mar/2025:09:19:25 +0000 "POST /sources/ldap.queries.php" 200`

I have also looked in the event logs on the Domain Controller and there are no entries, so it is as if it isn't even trying to connect.  I have also confirmed there is nothing blocked by the firewall in between.

Here is my config:

`Hosts: dc01.corp.mydomain.com
LDAP port: 636
BaseDN: DC=corp,DC=mydomain,DC=com
Username: CN=LDAP_Serv,OU=Service accounts,OU=Users,OU=All sites,OU=Sites,OU=AIM,DC=corp,DC=mydomain,DC=com
Password: **********
User Distinguished Name: distinguishedname
User name attribute: sAMAccountName
LDAPS: Yes
LDAP GUID Attribute: objectguid
`

**Comment by Adeline-44** [comment]
The same for me now

**Comment by nilsteampassnet** [comment]
@DaveWebb2 
Can you try
User name attribute: samaccountName

**Comment by DaveWebb2** [comment]
@nilsteampassnet Unfortunately that made no difference

**Comment by nilsteampassnet** [comment]
V2 and v3 are not using same parameters.
The library has changed and relies now on ldaprecord
So you need to setup from scratch

**Comment by nilsteampassnet** [comment]
Take a look to the AD server logs perhaps to see the queries sent by teampass

**Comment by reginfo** [comment]
I have tried clean install. 
After setup email and LDAP - tests pass.
Trying to add new AD user - nothing happens. 
User is visible on Users page:
<img width="696" alt="Image" src="https://github.com/user-attachments/assets/988394fa-8d94-4675-b16d-44ae8c949732" />

In Task Manager no In progress job.
<img width="482" alt="Image" src="https://github.com/user-attachments/assets/809b7489-7e63-43d1-aab0-9a6c1fa276d0" />

Only one Done job after I try to login as User. 

<img width="691" alt="Image" src="https://github.com/user-attachments/assets/e5972ab9-06a5-434c-a979-ec61a767f9c9" />

If I login as AD user, I can see:

<img width="384" alt="Image" src="https://github.com/user-attachments/assets/f2c90744-817b-4d93-a7ba-534c92f7f947" />
<img width="242" alt="Image" src="https://github.com/user-attachments/assets/20055a68-e3ca-4fb0-b158-7af3a3302baf" />

No email with code. 
 
In access.log I can see:
> 192.168.xx.xx - - [14/Mar/2025:17:36:47 +0200] "GET /sources/logs.datatables.php?action=tasks_finished&draw=1&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=5&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=6&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=true&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=2&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1741966599029 HTTP/1.1" 200 497 "https://xxxxx-test.xx.xx/index.php?page=tasks" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36 Edg/134.0.0.0"


I try to delete user and add it again. 
Receive console error: 

> index.php?page=users:3392 Table redrawn
index.php?page=users:3392 Table redrawn
index.php?page=users:3392 Table redrawn
index.php:1  Blocked aria-hidden on an element because its descendant retained focus. The focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.
Element with focus: button
Ancestor with aria-hidden:  <div class=​"modal fade" id=​"warningModal" tabindex=​"-1" aria-labelledby=​"Caution" style=​"display:​ block;​ padding-right:​ 15px;​" aria-hidden=​"true">​…​</div>​
index.php?page=users:3392 Table redrawn

And 

<img width="272" alt="Image" src="https://github.com/user-attachments/assets/519420c2-931c-4b41-9dce-7f8db862bd29" />

And still nothing. 

Interesting, nothing in error.log

**Comment by DaveWebb2** [comment]
There is nothing in the AD logs, it errors pretty quickly as if it isn't even starting a connection.

**Comment by reginfo** [comment]
> I have tried clean install. After setup email and LDAP - tests pass. Trying to add new AD user - nothing happens. User is visible on Users page: <img alt="Image" width="696" src="https://private-user-images.githubusercontent.com/4628571/422858208-988394fa-8d94-4675-b16d-44ae8c949732.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDIwNjczMzQsIm5iZiI6MTc0MjA2NzAzNCwicGF0aCI6Ii80NjI4NTcxLzQyMjg1ODIwOC05ODgzOTRmYS04ZDk0LTQ2NzUtYjE2ZC00NGFlOGM5NDk3MzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMTVUMTkzMDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzhiNmZjOTU0NzViODZkNzc0MWNjZjdlMWM5NjY0NWI0YmQyNGFjOTU4Y2JiMmI0ZmIyODQxMzY1MWI0YzQ0MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ni-bijZYO6NOmoDydDV0U839bxqDqaOnod07Rm4lBuc">
> 
> In Task Manager no In progress job. <img alt="Image" width="482" src="https://private-user-images.githubusercontent.com/4628571/422856498-809b7489-7e63-43d1-aab0-9a6c1fa276d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDIwNjczMzQsIm5iZiI6MTc0MjA2NzAzNCwicGF0aCI6Ii80NjI4NTcxLzQyMjg1NjQ5OC04MDliNzQ4OS03ZTYzLTQzZDEtYWFiMC05YTZjMWZhMjc2ZDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMTVUMTkzMDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWRhNjI4YTE3YjYwNWFkOGNkODk4NjdiYTBkY2JiMmUyYjJkNGUyZTBkNTdlNWIzMjhlN2ViY2JhZDhlNTQyOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.IyFu0DuO29JsQte7PJq558yV2RzBR_ypxDFrSFPWPbg">
> 
> Only one Done job after I try to login as User.
> 
> <img alt="Image" width="691" src="https://private-user-images.githubusercontent.com/4628571/422856694-e5972ab9-06a5-434c-a979-ec61a767f9c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDIwNjczMzQsIm5iZiI6MTc0MjA2NzAzNCwicGF0aCI6Ii80NjI4NTcxLzQyMjg1NjY5NC1lNTk3MmFiOS0wNmE1LTQzNGMtYTk3OS1lYzYxYTc2N2Y5YzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMTVUMTkzMDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWY0MzlhZDNjYTA2OWI5YWNkMDcyYWYyNjE5MGNhZWE4ZmQ5NjU0MjdmNTUwYjY1MmVkOGRlZjU3MTFlMjVmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.asPdxzB3pB3gElWnjKmRaOuBOYSagKDqg4yWThCmocs">
> If I login as AD user, I can see:
> 
> <img alt="Image" width="384" src="https://private-user-images.githubusercontent.com/4628571/422857008-f2c90744-817b-4d93-a7ba-534c92f7f947.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDIwNjczMzQsIm5iZiI6MTc0MjA2NzAzNCwicGF0aCI6Ii80NjI4NTcxLzQyMjg1NzAwOC1mMmM5MDc0NC04MTdiLTRkOTMtYTdiYS01MzRjOTJmN2Y5NDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMTVUMTkzMDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzMxOGIxZGFlY2MxMjdiNDljZDFjYThhMWJjNTNjMmEwOTk3ZjcyNDdiMWI2NzRhNmU4YzQ5N2RhMWY1NTY3YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.UZNgVuWScexjvdnHPhI5cQ55iguqBoFN-o_MzGoTgPo"> <img alt="Image" width="242" src="https://private-user-images.githubusercontent.com/4628571/422857107-20055a68-e3ca-4fb0-b158-7af3a3302baf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDIwNjczMzQsIm5iZiI6MTc0MjA2NzAzNCwicGF0aCI6Ii80NjI4NTcxLzQyMjg1NzEwNy0yMDA1NWE2OC1lM2NhLTRmYjAtYjE1OC03YWYzYTMzMDJiYWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMTVUMTkzMDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTI3N2QzYzBhOGRlZmY4YjMxN2FlNDQ5ZGE2NTU4MDMyN2Y3NzY5MzRkMTkzYzZiMzc5YzYwNjdhNjExYWI5ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.P417zyLtHGa3WFjIr6hT2HSALCiwZLrRM5oTj2yknzQ">
> No email with code.
> 
> In access.log I can see:
> 
> > 192.168.xx.xx - - [14/Mar/2025:17:36:47 +0200] "GET /sources/logs.datatables.php?action=tasks_finished&draw=1&columns%5B0%5D%5Bdata%5D=0&columns%5B0%5D%5Bname%5D=&columns%5B0%5D%5Bsearchable%5D=true&columns%5B0%5D%5Borderable%5D=true&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=1&columns%5B1%5D%5Bname%5D=&columns%5B1%5D%5Bsearchable%5D=true&columns%5B1%5D%5Borderable%5D=true&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B2%5D%5Bdata%5D=2&columns%5B2%5D%5Bname%5D=&columns%5B2%5D%5Bsearchable%5D=true&columns%5B2%5D%5Borderable%5D=true&columns%5B2%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B2%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B3%5D%5Bdata%5D=3&columns%5B3%5D%5Bname%5D=&columns%5B3%5D%5Bsearchable%5D=true&columns%5B3%5D%5Borderable%5D=true&columns%5B3%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B3%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B4%5D%5Bdata%5D=4&columns%5B4%5D%5Bname%5D=&columns%5B4%5D%5Bsearchable%5D=true&columns%5B4%5D%5Borderable%5D=true&columns%5B4%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B4%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B5%5D%5Bdata%5D=5&columns%5B5%5D%5Bname%5D=&columns%5B5%5D%5Bsearchable%5D=true&columns%5B5%5D%5Borderable%5D=true&columns%5B5%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B5%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B6%5D%5Bdata%5D=6&columns%5B6%5D%5Bname%5D=&columns%5B6%5D%5Bsearchable%5D=true&columns%5B6%5D%5Borderable%5D=true&columns%5B6%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B6%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=2&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1741966599029 HTTP/1.1" 200 497 "https://xxxxx-test.xx.xx/index.php?page=tasks" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36 Edg/134.0.0.0"
> 
> I try to delete user and add it again. Receive console error:
> 
> > index.php?page=users:3392 Table redrawn
> > index.php?page=users:3392 Table redrawn
> > index.php?page=users:3392 Table redrawn
> > index.php:1  Blocked aria-hidden on an element because its descendant retained focus. The focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden.
> > Element with focus: button
> > Ancestor with aria-hidden:  <div class=​"modal fade" id=​"warningModal" tabindex=​"-1" aria-labelledby=​"Caution" style=​"display:​ block;​ padding-right:​ 15px;​" aria-hidden=​"true">​…​​
> > index.php?page=users:3392 Table redrawn
> 
> And
> 
> <img alt="Image" width="272" src="https://private-user-images.githubusercontent.com/4628571/422859850-519420c2-931c-4b41-9dce-7f8db862bd29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDIwNjczMzQsIm5iZiI6MTc0MjA2NzAzNCwicGF0aCI6Ii80NjI4NTcxLzQyMjg1OTg1MC01MTk0MjBjMi05MzFjLTRiNDEtOWRjZS03ZjhkYjg2MmJkMjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMTVUMTkzMDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2Y1NmU1ZjBjNDhkZTFlM2UzYjQ3OTc5NTY2OWYxNTE1YjE4MjYxMGZhYzJjYWUyMGI0ZDQ5NTUzZDA5YTdhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.vUMmpJW1hjbVgl4foPX42uFgCuvgg53qjwpZdQwMbkU">
> And still nothing.
> 
> Interesting, nothing in error.log

For me seems in 3.1.4.5 this issue was fixed. 
Just one remark, when you add/choose LDAP user, don`t switch pages to quickly. After 3.1.4.5 after selecting user i was switch to different page to fast (didn`t get Temporary code) and task was not started.  I delete user/added and receive code and task was created. 

![Image](https://github.com/user-attachments/assets/a5bebc2e-14fe-49f1-aa89-f2ba2fa24a54)

**Comment by DaveWebb2** [comment]
I have upgraded to 3.1.4.6 and the problem remains.

I'll see if I can find a way to test ldaprecord from the command line.  Does anyone have any examples of how to do this?

**Comment by DaveWebb2** [comment]
For info, when I log in as admin and navigate to Utilities -> Logs there is nothing listed under Failed Logins or Errors.

**Comment by Icom82** [comment]
Hello!
I have just set the parameters for LDAP and am trying to pass the test. The system says there is an error connecting to the server, but I don't see any errors in the apache 2 logs. The documentation is outdated on the site. teampass.net in the file include.php I found the DEBUGLDAP option and set the value to true. However, I don't see any errors in the apache logs, the system log, or any log files like /files/ldap.debug.txt

How to debug?

**Comment by skt-jdrzik** [comment]
Hello, I found similar bug in teampass and LDAP AD integration, but I do not know If it is bug in teampass code, I must debug it deeper... If I try debug it I found it has transfer entries but all attributes are in lower case I have modified teampass JS code whis way and it was functional again:
```
diff --git a/pages/users.js.php b/pages/users.js.php
index fa23328b4..1a4936bf4 100755
--- a/pages/users.js.php
+++ b/pages/users.js.php
@@ -2066,8 +2066,11 @@ if ($checkUserAccess->checkSession() === false || $checkUserAccess->userAccessPa
                         userLogin,
                         group;
                     var entry;
-                    $.each(data.entries, function(i, entry) {
-                        userLogin = entry[store.get('teampassSettings').ldap_user_attribute] !== undefined ? entry[store.get('teampassSettings').ldap_user_attribute][0] : '';
+                   $.each(data.entries, function(i, entry) {
+                       userLogin = entry[store.get('teampassSettings').ldap_user_attribute.toLowerCase()] !== undefined ? entry[store.get('teampassSettings').ldap_user_attribute.toLowerCase()][0] : '';
                         // CHeck if not empty
                         if (userLogin !== '') {
                             html += '<tr>' +

```

**Comment by BigAndini** [comment]
Hello, 

I encounter a similar issue.

I've tracked the network traffic and get a clear Unkown CA, while an own script that uses ldap_bind_ext can connect with the same credentials. Since teampass uses LdapRecord as library, I copied the whole vendor folder to a test folder and created a small script with my credentials based on the LdapRecord Example from here: https://ldaprecord.com/docs/core/v2/configuration/#hosts as well with a positive Feedback. So it seems only some sort of Teampass combination doesn't want to connect to the AD.

I also tried to set the according TLS_CACERT file in:
- /etc/openldap/ldap.conf since php uses the same library
- with systemctl edit httpd to set it as environment variable to the webserver
- with SetEnv in the httpd configuration
- with php-fpm environment variable
- with php.ini setting
- with putenv within the Teampass code
- with additional LDAP_OPT_X_TLS_CACERTFILE parameter for the connection

Nothing brought the connection up.

Are there any further ideas or any further requirements for information to debug this issue?

Regards,
Andreas
