### ISSUE TITLE
error Item is currently being updated and cannot be edited

### ISSUE THREAD

**Issue by alezannaSB** [nilsteampassnet/TeamPass#4734]
### Page on which it happened
index.php?page=items

### Steps to reproduce
1. Open a folder, try to add a new item: error Item is currently being updated and cannot be edited.
2. Open same folder, click on an existing item, them click con new item: new form opens and item can be added.
3. Return to item list on a folder, without an opened item, click on ew item: error Item is currently being updated and cannot be edited
This happens in both http and https connections

### Expected behaviour
Expected is that I can just click on a new item and create it, as it was on previous versions, can get if it's a version bug or a misconfigured installation.

### Actual behaviour
Trying to add a new item in a folder get the error "Item is currently being updated and cannot be edited." if I am just inside the folder and I have not opened another item

### Server configuration
**Operating system**: Linux srvsbteampass02 5.15.0-140-generic #150-Ubuntu SMP Sat Apr 12 06:00:09 UTC 2025 x86_64

**Web server:** Apache/2.4.52 (Ubuntu)

**Database:** 10.6.22-MariaDB-0ubuntu0.22.04.1

**PHP version:** 8.1.30

**Teampass version:** 3.1.4.20

**Teampass configuration variables:**
```
'activate_expiration' =&gt; '0'
'admin_2fa_required' =&gt; '1'
'agses_authentication_enabled' =&gt; '0'
'allow_import' =&gt; '0'
'allow_print' =&gt; '1'
'anyone_can_modify' =&gt; '0'
'anyone_can_modify_bydefault' =&gt; '0'
'api' =&gt; '0'
'api_token_duration' =&gt; '60'
'bck_script_filename' =&gt; 'bck_teampass'
'bck_script_passkey' =&gt; ''
'bck_script_path' =&gt; '/var/www/html/teampass/backups'
'clean_orphan_objects_task' =&gt; ''
'clipboard_life_duration' =&gt; '30'
'copy_to_clipboard_small_icons' =&gt; '1'
'cpassman_dir' =&gt; '/var/www/html/teampass'
'cpassman_url' =&gt; 'https:///teampass'
'create_item_without_password' =&gt; '1'
'custom_login_text' =&gt; ''
'custom_logo' =&gt; ''
'date_format' =&gt; 'd/m/Y'
'default_language' =&gt; 'english'
'default_session_expiration_time' =&gt; '120'
'delay_item_edition' =&gt; '0'
'disable_show_forgot_pwd_link' =&gt; '0'
'duo' =&gt; '0'
'duo_failmode' =&gt; 'secure'
'duo_host' =&gt; ''
'duo_ikey' =&gt; ''
'duo_skey' =&gt; ''
'duplicate_folder' =&gt; '0'
'duplicate_item' =&gt; '1'
'email_auth_pwd' =&gt; ''
'email_auth_username' =&gt; ''
'email_debug_level' =&gt; '0'
'email_from' =&gt; ''
'email_from_name' =&gt; 'Teampass'
'email_port' =&gt; '25'
'email_security' =&gt; ''
'email_server_url' =&gt; ''
'email_smtp_auth' =&gt; ''
'email_smtp_server' =&gt; ''
'enable_ad_user_auto_creation' =&gt; '0'
'enable_ad_users_with_ad_groups' =&gt; '0'
'enable_attachment_encryption' =&gt; '1'
'enable_delete_after_consultation' =&gt; '0'
'enable_email_notification_on_item_shown' =&gt; '0'
'enable_email_notification_on_user_pw_change' =&gt; '0'
'enable_favourites' =&gt; '1'
'enable_http_request_login' =&gt; '0'
'enable_kb' =&gt; '0'
'enable_massive_move_delete' =&gt; '1'
'enable_personal_saltkey_cookie' =&gt; '0'
'enable_pf_feature' =&gt; '0'
'enable_refresh_task_last_execution' =&gt; '1'
'enable_send_email_on_user_login' =&gt; '0'
'enable_server_password_change' =&gt; '0'
'enable_sts' =&gt; '0'
'enable_suggestion' =&gt; '0'
'enable_tasks_log' =&gt; '0'
'enable_tasks_manager' =&gt; '1'
'enable_user_can_create_folders' =&gt; '1'
'encryptClientServer' =&gt; '1'
'favicon' =&gt; 'https:///teampass/favicon.ico'
'files_with_defuse' =&gt; 'done'
'ga_reset_by_user' =&gt; ''
'ga_website_name' =&gt; 'TeamPass San Benedetto'
'get_tp_info' =&gt; '0'
'google_authentication' =&gt; '0'
'highlight_favorites' =&gt; '0'
'highlight_selected' =&gt; '1'
'insert_manual_entry_item_history' =&gt; '0'
'item_duplicate_in_same_folder' =&gt; '1'
'item_extra_fields' =&gt; '0'
'items_ops_job_frequency' =&gt; '1'
'items_statistics_job_frequency' =&gt; '5'
'last_cron_exec' =&gt; '1748261161'
'ldap_and_local_authentication' =&gt; '1'
'ldap_bdn' =&gt; 'OU=Direzione Sistemi Informativi,OU=Departments,OU=OU Utenti Scorze,OU=UsersSB,DC=sanbenedetto,DC=local'
'ldap_dn_additional_user_dn' =&gt; ''
'ldap_group_object_filter' =&gt; ''
'ldap_group_objectclasses_attibute' =&gt; 'top,group'
'ldap_guid_attibute' =&gt; 'objectGUID'
'ldap_hosts' =&gt; ''
'ldap_mode' =&gt; '1'
'ldap_new_user_is_administrated_by' =&gt; '0'
'ldap_password' =&gt; ''
'ldap_port' =&gt; '389'
'ldap_ssl' =&gt; '0'
'ldap_tls' =&gt; '0'
'ldap_tls_certifacte_check' =&gt; 'LDAP_OPT_X_TLS_NEVER'
'ldap_type' =&gt; 'ActiveDirectory'
'ldap_user_attribute' =&gt; 'samaccountname'
'ldap_user_dn_attribute' =&gt; 'distinguishedname'
'ldap_user_object_filter' =&gt; '(objectClass=Person)'
'ldap_username' =&gt; 'CN=ldap search,OU=IT_Service,OU=IT,OU=OU Utenti Scorze,OU=UsersSB,DC=sanbenedetto,DC=local'
'limited_search_default' =&gt; '0'
'log_accessed' =&gt; '1'
'log_connections' =&gt; '1'
'maintenance_mode' =&gt; '0'
'manager_edit' =&gt; '1'
'manager_move_item' =&gt; '1'
'max_latest_items' =&gt; '10'
'maximum_number_of_items_to_treat' =&gt; '100'
'maximum_session_expiration_time' =&gt; '120'
'mfa_for_roles' =&gt; ''
'migration_to_2127' =&gt; 'done'
'nb_bad_authentication' =&gt; '0'
'nb_items_by_query' =&gt; 'auto'
'number_of_used_pw' =&gt; '3'
'number_users_build_cache_tree' =&gt; '10'
'oauth2_client_appname' =&gt; 'Login with Azure'
'oauth2_client_endpoint' =&gt; ''
'oauth2_client_id' =&gt; ''
'oauth2_client_scopes' =&gt; 'openid,profile,email,User.Read,Group.Read.All'
'oauth2_client_secret' =&gt; ''
'oauth2_client_token' =&gt; ''
'oauth2_client_urlResourceOwnerDetails' =&gt; ''
'oauth2_enabled' =&gt; '0'
'oauth2_tenant_id' =&gt; ''
'oauth_new_user_is_administrated_by' =&gt; '0'
'oauth_self_register_groups' =&gt; ''
'oauth_selfregistered_user_belongs_to_role' =&gt; '0'
'offline_key_level' =&gt; '0'
'onthefly-backup-key' =&gt; ''
'onthefly-restore-key' =&gt; ''
'otv_expiration_period' =&gt; '7'
'otv_is_enabled' =&gt; '0'
'password_overview_delay' =&gt; '10'
'path_to_files_folder' =&gt; '/var/www/html/teampass/files'
'path_to_upload_folder' =&gt; '/var/www/html/teampass/upload'
'personal_saltkey_cookie_duration' =&gt; '31'
'personal_saltkey_security_level' =&gt; '50'
'proxy_ip' =&gt; ''
'proxy_port' =&gt; ''
'purge_temporary_files_task' =&gt; ''
'pw_life_duration' =&gt; '0'
'pwd_default_length' =&gt; '10'
'pwd_maximum_length' =&gt; '40'
'rebuild_config_file' =&gt; ''
'reload_cache_table_task' =&gt; ''
'restricted_to' =&gt; '0'
'restricted_to_roles' =&gt; '0'
'richtext' =&gt; '0'
'roles_allowed_to_print' =&gt; '0'
'roles_allowed_to_print_select' =&gt; '[7]'
'saltkey_ante_2127' =&gt; 'none'
'secure_display_image' =&gt; '1'
'send_mail_on_user_login' =&gt; '0'
'send_statistics_items' =&gt; 'stat_country;stat_users;stat_items;stat_items_shared;stat_folders;stat_folders_shared;stat_admins;stat_managers;stat_ro;stat_mysqlversion;stat_phpversion;stat_teampassversion;stat_languages;stat_kb;stat_suggestion;stat_customfields;stat_api;stat_2fa;stat_agses;stat_duo;stat_ldap;stat_syslog;stat_stricthttps;stat_fav;stat_pf;'
'send_stats' =&gt; '0'
'send_stats_time' =&gt; '1725971683'
'sending_emails_job_frequency' =&gt; '2'
'settings_offline_mode' =&gt; '0'
'settings_tree_counters' =&gt; '0'
'show_description' =&gt; '1'
'show_item_data' =&gt; '1'
'show_last_items' =&gt; '1'
'show_only_accessible_folders' =&gt; '1'
'subfolder_rights_as_parent' =&gt; '1'
'syslog_enable' =&gt; '0'
'syslog_host' =&gt; ''
'syslog_port' =&gt; '514'
'task_maximum_run_time' =&gt; '300'
'tasks_history_delay' =&gt; '604800'
'tasks_log_retention_delay' =&gt; '30'
'tasks_manager_refreshing_period' =&gt; '20'
'teampass_version' =&gt; '3.1.4'
'time_format' =&gt; 'H:i:s'
'timestamp' =&gt; '1748261197'
'timezone' =&gt; 'Europe/Rome'
'tree_counters' =&gt; '0'
'upgrade_timestamp' =&gt; '1748258736'
'upload_all_extensions_file' =&gt; '0'
'upload_docext' =&gt; 'doc,docx,dotx,xls,xlsx,xltx,rtf,csv,txt,pdf,ppt,pptx,pot,dotx,xltx'
'upload_imageresize_height' =&gt; '600'
'upload_imageresize_options' =&gt; '1'
'upload_imageresize_quality' =&gt; '90'
'upload_imageresize_width' =&gt; '800'
'upload_imagesext' =&gt; 'jpg,jpeg,gif,png'
'upload_maxfilesize' =&gt; '10mb'
'upload_otherext' =&gt; 'sql,xml'
'upload_pkgext' =&gt; '7z,rar,tar,zip'
'upload_zero_byte_file' =&gt; '0'
'url_to_files_folder' =&gt; 'http://10.168.104.41/teampass/files'
'use_md5_password_as_salt' =&gt; '0'
'user_keys_job_frequency' =&gt; '1'
'users_personal_folder_task' =&gt; ''
'utf8_enabled' =&gt; '1'

```

**Updated from an older Teampass or fresh install:**

### Client configuration

**Browser:** Chrome - 136.0.0.0

**Operating system:** Windows - 64bits

#### Web server error log
```
 -  ()
```

#### Teampass 10 last system errors
```

```

#### Log from the web-browser developer console (CTRL + SHIFT + i)
```
SHOW NEW ITEM
index.php?page=items:4862 >>> #folders-tree-card -- 
index.php?page=items:10051 Get privilege for folder 7
index.php?page=items:8285 {itemId: NaN, treeId: 7, userId: 10000000, actionType: 'edit'}actionType: "edit"itemId: NaNtreeId: 7userId: 10000000[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
index.php?page=items:8299 DEBUG: checkAccess
index.php?page=items:8300 
```

**Comment by guerricv** [comment]
Same issue on my side.

In another post :
https://github.com/nilsteampassnet/TeamPass/issues/4721

SamuelSilvaG told that he had to grand access on the folder for each users but I tried everything, not working for me. btw I have too much folders to manage folder by folder.

**Comment by guerricv** [comment]
indeed, i have some items here :

MariaDB [teampassdb]> select * FROM `teampass_items_edition`;
+--------------+---------+----------+------------+
| increment_id | item_id | user_id  | timestamp  |
+--------------+---------+----------+------------+
|         1479 |    1340 | 10000122 | 1748433202 |
|         1480 |     635 | 10000067 | 1748417174 |
|         1481 |     340 | 10000067 | 1748417203 |
|         1482 |    1372 | 10000128 | 1748416983 |
|         1483 |    1373 | 10000128 | 1748416984 |
|         1484 |     610 | 10000052 | 1748421771 |
|         1485 |     446 | 10000028 | 1748428401 |
|         1486 |    1470 | 10000097 | 1748434647 |
|         1487 |    1471 | 10000097 | 1748435365 |
|         1488 |       0 | 10000097 | 1748443426 |
|         1490 |    1473 | 10000097 | 1748435702 |
|         1491 |    1472 | 10000097 | 1748435827 |
|         1492 |    1474 | 10000097 | 1748435903 |
|         1493 |    1475 | 10000097 | 1748435977 |
|         1494 |    1476 | 10000097 | 1748436093 |
|         1495 |     206 | 10000018 | 1748436511 |
|         1496 |     440 | 10000028 | 1748437095 |
|         1497 |     614 | 10000067 | 1748439369 |
|         1498 |    1084 | 10000025 | 1748440820 |
|         1499 |    1211 | 10000025 | 1748440860 |
|         1500 |    1210 | 10000025 | 1748440890 |
|         1501 |     566 | 10000025 | 1748440913 |
|         1502 |     944 | 10000032 | 1748441842 |
|         1503 |    1196 | 10000122 | 1748442087 |
|         1505 |    1477 | 10000097 | 1748443631 |
|         1506 |    1478 | 10000097 | 1748443685 |
|         1507 |    1479 | 10000097 | 1748443741 |
|         1508 |    1197 | 10000024 | 1748444176 |
|         1509 |    1480 | 10000024 | 1748444220 |
|         1510 |    1180 | 10000091 | 1748446892 |
+--------------+---------+----------+------------+
30 rows in set (0.000 sec)


while current task manager is empty

**Comment by alezannaSB** [comment]
Here's the output, thanks!

MariaDB [teampass]> select * FROM `teampass_items_edition`;
+--------------+---------+----------+------------+
| increment_id | item_id | user_id  | timestamp  |
+--------------+---------+----------+------------+
|          436 |     475 | 10000005 | 1748441106 |
|          437 |     888 | 10000019 | 1748434417 |
|          439 |     474 | 10000006 | 1748434897 |
|          440 |    1202 | 10000033 | 1748436736 |
|          441 |    1210 | 10000033 | 1748436844 |
|          442 |     457 | 10000006 | 1748439493 |
|          443 |     410 | 10000016 | 1748506602 |
|          444 |     848 | 10000016 | 1748506614 |
+--------------+---------+----------+------------+
8 rows in set (0.000 sec)

**Comment by nilsteampassnet** [comment]
Ok I see.
I will investigate

**Comment by guerricv** [comment]
Issue is fixed with the last release. Thanks a lot Nils !

**Comment by alezannaSB** [comment]
Hello, sadly I still have the issue in latest version 3.1.4.23, I have already cleared cache/cookies of Chrome and tried inPrivate browsing: 

![Image](https://github.com/user-attachments/assets/e31e7956-ae90-4f13-8090-79d540dad5ff)

**Comment by alezannaSB** [comment]
I have tried to make a full whole new installation of Teampass on another server with updated os and packages, to check if it was an installation or server issue, but I was not able to export/import all items from old to new installation, I tried to correctly format the csv as found on the instructions (label,login,password,url,comments), but it always skips the "comments" section, attachments or images are not exported and sadly csv import gives error if passwords or comments contain a "," inside
