### ISSUE TITLE
Ldap user login stays "in progress" forever after update from 3.1.5.1 to 3.1.5.13

### ISSUE THREAD

**Issue by alezannaSB** [nilsteampassnet/TeamPass#4978]
Hello, after update from 3.1.5.1 to 3.1.5.13 user managed throug AD/ldap are stuck with "in progress" banner on top, but never loggin in.
Settings in ldap section are correct and testing a user goes well, local administrator can login, issue seems to be releated only to ldap managed users, but it gives no error, just stays "in progress".. we rolled back to 3.1.5.1 for now

**Comment by jpboureau** [comment]
Already reported in issue #4970

**Comment by Sky-W-ui** [comment]
I have a similar issue with local users in 3.1.5.12. Sometimes Users are stuck in logging in.
If you reload the page then the user is logged in and can work with teampass.
But this happen only sometimes.
Sometimes it needs a few seconds longer and sometimes you are logged in immediately.

**Comment by guerricv** [comment]
Same issue on my side with version 3.1.5.12. I haven't try with the last release yet.
I just need to click "connect" again to be log in.

**Comment by guerricv** [comment]
I've just tried with version 3.1.5.13 on a testing environnemnt. The issue seems fixed with this version.

**Comment by Sky-W-ui** [comment]
//i have no issues aswell after update to 3.1.5.13

edit: I have to correct my statement. The problem persists in 3.1.5.13 on my side

**Comment by DaveWebb2** [comment]
I have this issue in 3.1.5.13 while using oAuth2.  Everyone has to refresh the page after logging in to get past the "In progress" banner at the top.

**Comment by nilsteampassnet** [comment]
I think this issue is solved in latest release delivered yesterday.
I fixed an instruction I identified during code review that could be the 
cause of the behavior discussed here.
